# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

import types

__config__ = pulumi.Config('systeam')


class _ExportableConfig(types.ModuleType):
    @property
    def api_token(self) -> Optional[str]:
        """
        PAT token for API authentication. Can also be set via SYSTEAM_API_TOKEN environment variable.
        """
        return __config__.get('apiToken')

    @property
    def api_url(self) -> Optional[str]:
        """
        Base URL of the SysTeam Healthchecks API. Can also be set via SYSTEAM_API_URL environment variable.
        """
        return __config__.get('apiUrl')

