# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .agent_registration_token import *
from .check import *
from .check_slo import *
from .contact_method import *
from .escalation_policy import *
from .get_escalation_policy import *
from .get_notification_channel import *
from .get_oncall_schedule import *
from .get_organization import *
from .get_project import *
from .get_service import *
from .get_team import *
from .integration_key import *
from .lifecycle_watch import *
from .maintenance_window import *
from .notification_channel import *
from .oncall_schedule import *
from .playbook import *
from .project import *
from .provider import *
from .service import *
from .status_page import *
from .team import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_systeam.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_systeam.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "systeam",
  "mod": "index/agentRegistrationToken",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/agentRegistrationToken:AgentRegistrationToken": "AgentRegistrationToken"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/check",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/check:Check": "Check"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/checkSlo",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/checkSlo:CheckSlo": "CheckSlo"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/contactMethod",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/contactMethod:ContactMethod": "ContactMethod"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/escalationPolicy",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/escalationPolicy:EscalationPolicy": "EscalationPolicy"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/integrationKey",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/integrationKey:IntegrationKey": "IntegrationKey"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/lifecycleWatch",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/lifecycleWatch:LifecycleWatch": "LifecycleWatch"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/maintenanceWindow",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/maintenanceWindow:MaintenanceWindow": "MaintenanceWindow"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/notificationChannel",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/notificationChannel:NotificationChannel": "NotificationChannel"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/oncallSchedule",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/oncallSchedule:OncallSchedule": "OncallSchedule"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/playbook",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/playbook:Playbook": "Playbook"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/project",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/project:Project": "Project"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/service",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/service:Service": "Service"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/statusPage",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/statusPage:StatusPage": "StatusPage"
  }
 },
 {
  "pkg": "systeam",
  "mod": "index/team",
  "fqn": "pulumi_systeam",
  "classes": {
   "systeam:index/team:Team": "Team"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "systeam",
  "token": "pulumi:providers:systeam",
  "fqn": "pulumi_systeam",
  "class": "Provider"
 }
]
"""
)
