# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'EscalationPolicyStepArgs',
    'EscalationPolicyStepArgsDict',
    'OncallScheduleParticipantArgs',
    'OncallScheduleParticipantArgsDict',
    'PlaybookStepArgs',
    'PlaybookStepArgsDict',
]

MYPY = False

if not MYPY:
    class EscalationPolicyStepArgsDict(TypedDict):
        step_order: pulumi.Input[int]
        """
        Order of this step in the escalation chain (1-based).
        """
        target_type: pulumi.Input[str]
        """
        Type of escalation target: user, schedule, or channel.
        """
        delay_minutes: NotRequired[pulumi.Input[int]]
        """
        Delay in minutes before escalating to this step.
        """
        target_channel_id: NotRequired[pulumi.Input[int]]
        """
        ID of the target notification channel (when target_type is 'channel').
        """
        target_schedule_id: NotRequired[pulumi.Input[int]]
        """
        ID of the target on-call schedule (when target_type is 'schedule').
        """
        target_user_id: NotRequired[pulumi.Input[int]]
        """
        ID of the target user (when target_type is 'user').
        """
elif False:
    EscalationPolicyStepArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class EscalationPolicyStepArgs:
    def __init__(__self__, *,
                 step_order: pulumi.Input[int],
                 target_type: pulumi.Input[str],
                 delay_minutes: Optional[pulumi.Input[int]] = None,
                 target_channel_id: Optional[pulumi.Input[int]] = None,
                 target_schedule_id: Optional[pulumi.Input[int]] = None,
                 target_user_id: Optional[pulumi.Input[int]] = None):
        """
        :param pulumi.Input[int] step_order: Order of this step in the escalation chain (1-based).
        :param pulumi.Input[str] target_type: Type of escalation target: user, schedule, or channel.
        :param pulumi.Input[int] delay_minutes: Delay in minutes before escalating to this step.
        :param pulumi.Input[int] target_channel_id: ID of the target notification channel (when target_type is 'channel').
        :param pulumi.Input[int] target_schedule_id: ID of the target on-call schedule (when target_type is 'schedule').
        :param pulumi.Input[int] target_user_id: ID of the target user (when target_type is 'user').
        """
        pulumi.set(__self__, "step_order", step_order)
        pulumi.set(__self__, "target_type", target_type)
        if delay_minutes is not None:
            pulumi.set(__self__, "delay_minutes", delay_minutes)
        if target_channel_id is not None:
            pulumi.set(__self__, "target_channel_id", target_channel_id)
        if target_schedule_id is not None:
            pulumi.set(__self__, "target_schedule_id", target_schedule_id)
        if target_user_id is not None:
            pulumi.set(__self__, "target_user_id", target_user_id)

    @property
    @pulumi.getter(name="stepOrder")
    def step_order(self) -> pulumi.Input[int]:
        """
        Order of this step in the escalation chain (1-based).
        """
        return pulumi.get(self, "step_order")

    @step_order.setter
    def step_order(self, value: pulumi.Input[int]):
        pulumi.set(self, "step_order", value)

    @property
    @pulumi.getter(name="targetType")
    def target_type(self) -> pulumi.Input[str]:
        """
        Type of escalation target: user, schedule, or channel.
        """
        return pulumi.get(self, "target_type")

    @target_type.setter
    def target_type(self, value: pulumi.Input[str]):
        pulumi.set(self, "target_type", value)

    @property
    @pulumi.getter(name="delayMinutes")
    def delay_minutes(self) -> Optional[pulumi.Input[int]]:
        """
        Delay in minutes before escalating to this step.
        """
        return pulumi.get(self, "delay_minutes")

    @delay_minutes.setter
    def delay_minutes(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "delay_minutes", value)

    @property
    @pulumi.getter(name="targetChannelId")
    def target_channel_id(self) -> Optional[pulumi.Input[int]]:
        """
        ID of the target notification channel (when target_type is 'channel').
        """
        return pulumi.get(self, "target_channel_id")

    @target_channel_id.setter
    def target_channel_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "target_channel_id", value)

    @property
    @pulumi.getter(name="targetScheduleId")
    def target_schedule_id(self) -> Optional[pulumi.Input[int]]:
        """
        ID of the target on-call schedule (when target_type is 'schedule').
        """
        return pulumi.get(self, "target_schedule_id")

    @target_schedule_id.setter
    def target_schedule_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "target_schedule_id", value)

    @property
    @pulumi.getter(name="targetUserId")
    def target_user_id(self) -> Optional[pulumi.Input[int]]:
        """
        ID of the target user (when target_type is 'user').
        """
        return pulumi.get(self, "target_user_id")

    @target_user_id.setter
    def target_user_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "target_user_id", value)


if not MYPY:
    class OncallScheduleParticipantArgsDict(TypedDict):
        user_id: pulumi.Input[int]
        """
        ID of the participant user.
        """
        position: NotRequired[pulumi.Input[int]]
        """
        Position in the rotation order.
        """
elif False:
    OncallScheduleParticipantArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class OncallScheduleParticipantArgs:
    def __init__(__self__, *,
                 user_id: pulumi.Input[int],
                 position: Optional[pulumi.Input[int]] = None):
        """
        :param pulumi.Input[int] user_id: ID of the participant user.
        :param pulumi.Input[int] position: Position in the rotation order.
        """
        pulumi.set(__self__, "user_id", user_id)
        if position is not None:
            pulumi.set(__self__, "position", position)

    @property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Input[int]:
        """
        ID of the participant user.
        """
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "user_id", value)

    @property
    @pulumi.getter
    def position(self) -> Optional[pulumi.Input[int]]:
        """
        Position in the rotation order.
        """
        return pulumi.get(self, "position")

    @position.setter
    def position(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "position", value)


if not MYPY:
    class PlaybookStepArgsDict(TypedDict):
        action_type: pulumi.Input[str]
        """
        The action to run. One of: add*responders, set*priority, set*severity, setup*war*room, create*jira*ticket, auto*ack, auto*resolve, update*status*page, notify*subscribers, run*escalation, outbound*webhook, create*slack*channel, add*links, title*enrichment, send*custom*notification, manual_step.
        """
        name: pulumi.Input[str]
        """
        Human-readable step name.
        """
        step_order: pulumi.Input[int]
        """
        Position of this step in the run (1-based).
        """
        conditions: NotRequired[pulumi.Input[str]]
        """
        Optional JSON array of conditions gating this step.
        """
        config: NotRequired[pulumi.Input[str]]
        """
        Action-specific configuration as a JSON object.
        """
        is_manual: NotRequired[pulumi.Input[bool]]
        """
        Whether the step waits for manual completion.
        """
        parallel_group: NotRequired[pulumi.Input[str]]
        """
        Steps sharing a parallel_group run concurrently.
        """
        timeout_seconds: NotRequired[pulumi.Input[int]]
        """
        Step timeout in seconds (1-120).
        """
elif False:
    PlaybookStepArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class PlaybookStepArgs:
    def __init__(__self__, *,
                 action_type: pulumi.Input[str],
                 name: pulumi.Input[str],
                 step_order: pulumi.Input[int],
                 conditions: Optional[pulumi.Input[str]] = None,
                 config: Optional[pulumi.Input[str]] = None,
                 is_manual: Optional[pulumi.Input[bool]] = None,
                 parallel_group: Optional[pulumi.Input[str]] = None,
                 timeout_seconds: Optional[pulumi.Input[int]] = None):
        """
        :param pulumi.Input[str] action_type: The action to run. One of: add*responders, set*priority, set*severity, setup*war*room, create*jira*ticket, auto*ack, auto*resolve, update*status*page, notify*subscribers, run*escalation, outbound*webhook, create*slack*channel, add*links, title*enrichment, send*custom*notification, manual_step.
        :param pulumi.Input[str] name: Human-readable step name.
        :param pulumi.Input[int] step_order: Position of this step in the run (1-based).
        :param pulumi.Input[str] conditions: Optional JSON array of conditions gating this step.
        :param pulumi.Input[str] config: Action-specific configuration as a JSON object.
        :param pulumi.Input[bool] is_manual: Whether the step waits for manual completion.
        :param pulumi.Input[str] parallel_group: Steps sharing a parallel_group run concurrently.
        :param pulumi.Input[int] timeout_seconds: Step timeout in seconds (1-120).
        """
        pulumi.set(__self__, "action_type", action_type)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "step_order", step_order)
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if is_manual is not None:
            pulumi.set(__self__, "is_manual", is_manual)
        if parallel_group is not None:
            pulumi.set(__self__, "parallel_group", parallel_group)
        if timeout_seconds is not None:
            pulumi.set(__self__, "timeout_seconds", timeout_seconds)

    @property
    @pulumi.getter(name="actionType")
    def action_type(self) -> pulumi.Input[str]:
        """
        The action to run. One of: add*responders, set*priority, set*severity, setup*war*room, create*jira*ticket, auto*ack, auto*resolve, update*status*page, notify*subscribers, run*escalation, outbound*webhook, create*slack*channel, add*links, title*enrichment, send*custom*notification, manual_step.
        """
        return pulumi.get(self, "action_type")

    @action_type.setter
    def action_type(self, value: pulumi.Input[str]):
        pulumi.set(self, "action_type", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        Human-readable step name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="stepOrder")
    def step_order(self) -> pulumi.Input[int]:
        """
        Position of this step in the run (1-based).
        """
        return pulumi.get(self, "step_order")

    @step_order.setter
    def step_order(self, value: pulumi.Input[int]):
        pulumi.set(self, "step_order", value)

    @property
    @pulumi.getter
    def conditions(self) -> Optional[pulumi.Input[str]]:
        """
        Optional JSON array of conditions gating this step.
        """
        return pulumi.get(self, "conditions")

    @conditions.setter
    def conditions(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "conditions", value)

    @property
    @pulumi.getter
    def config(self) -> Optional[pulumi.Input[str]]:
        """
        Action-specific configuration as a JSON object.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "config", value)

    @property
    @pulumi.getter(name="isManual")
    def is_manual(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the step waits for manual completion.
        """
        return pulumi.get(self, "is_manual")

    @is_manual.setter
    def is_manual(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_manual", value)

    @property
    @pulumi.getter(name="parallelGroup")
    def parallel_group(self) -> Optional[pulumi.Input[str]]:
        """
        Steps sharing a parallel_group run concurrently.
        """
        return pulumi.get(self, "parallel_group")

    @parallel_group.setter
    def parallel_group(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "parallel_group", value)

    @property
    @pulumi.getter(name="timeoutSeconds")
    def timeout_seconds(self) -> Optional[pulumi.Input[int]]:
        """
        Step timeout in seconds (1-120).
        """
        return pulumi.get(self, "timeout_seconds")

    @timeout_seconds.setter
    def timeout_seconds(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "timeout_seconds", value)


