# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['CheckSloArgs', 'CheckSlo']

@pulumi.input_type
class CheckSloArgs:
    def __init__(__self__, *,
                 check_id: pulumi.Input[int],
                 budget_warn_pct: Optional[pulumi.Input[float]] = None,
                 burn_rate_alert_enabled: Optional[pulumi.Input[bool]] = None,
                 burn_rate_threshold: Optional[pulumi.Input[float]] = None,
                 burn_rate_window_minutes: Optional[pulumi.Input[int]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 latency_threshold_ms: Optional[pulumi.Input[int]] = None,
                 notify_on_budget_exhausted: Optional[pulumi.Input[bool]] = None,
                 notify_on_budget_warn: Optional[pulumi.Input[bool]] = None,
                 sli_type: Optional[pulumi.Input[str]] = None,
                 target_percentage: Optional[pulumi.Input[float]] = None,
                 window_days: Optional[pulumi.Input[int]] = None):
        """
        The set of arguments for constructing a CheckSlo resource.
        :param pulumi.Input[int] check_id: The ID of the check this SLO belongs to.
        :param pulumi.Input[float] budget_warn_pct: Error budget warning threshold percentage.
        :param pulumi.Input[bool] burn_rate_alert_enabled: Whether burn rate alerts are enabled.
        :param pulumi.Input[float] burn_rate_threshold: Burn rate threshold for alerts.
        :param pulumi.Input[int] burn_rate_window_minutes: Burn rate evaluation window in minutes.
        :param pulumi.Input[bool] is_active: Whether the SLO is active.
        :param pulumi.Input[int] latency_threshold_ms: Latency threshold in milliseconds for latency-based SLIs.
        :param pulumi.Input[bool] notify_on_budget_exhausted: Send notification when error budget is exhausted.
        :param pulumi.Input[bool] notify_on_budget_warn: Send notification when error budget reaches warning threshold.
        :param pulumi.Input[str] sli_type: The SLI type. Currently only 'availability' is supported.
        :param pulumi.Input[float] target_percentage: The SLO target percentage (90.0 - 100.0).
        :param pulumi.Input[int] window_days: The SLO window in days (7, 30, or 90).
        """
        pulumi.set(__self__, "check_id", check_id)
        if budget_warn_pct is not None:
            pulumi.set(__self__, "budget_warn_pct", budget_warn_pct)
        if burn_rate_alert_enabled is not None:
            pulumi.set(__self__, "burn_rate_alert_enabled", burn_rate_alert_enabled)
        if burn_rate_threshold is not None:
            pulumi.set(__self__, "burn_rate_threshold", burn_rate_threshold)
        if burn_rate_window_minutes is not None:
            pulumi.set(__self__, "burn_rate_window_minutes", burn_rate_window_minutes)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if latency_threshold_ms is not None:
            pulumi.set(__self__, "latency_threshold_ms", latency_threshold_ms)
        if notify_on_budget_exhausted is not None:
            pulumi.set(__self__, "notify_on_budget_exhausted", notify_on_budget_exhausted)
        if notify_on_budget_warn is not None:
            pulumi.set(__self__, "notify_on_budget_warn", notify_on_budget_warn)
        if sli_type is not None:
            pulumi.set(__self__, "sli_type", sli_type)
        if target_percentage is not None:
            pulumi.set(__self__, "target_percentage", target_percentage)
        if window_days is not None:
            pulumi.set(__self__, "window_days", window_days)

    @property
    @pulumi.getter(name="checkId")
    def check_id(self) -> pulumi.Input[int]:
        """
        The ID of the check this SLO belongs to.
        """
        return pulumi.get(self, "check_id")

    @check_id.setter
    def check_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "check_id", value)

    @property
    @pulumi.getter(name="budgetWarnPct")
    def budget_warn_pct(self) -> Optional[pulumi.Input[float]]:
        """
        Error budget warning threshold percentage.
        """
        return pulumi.get(self, "budget_warn_pct")

    @budget_warn_pct.setter
    def budget_warn_pct(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "budget_warn_pct", value)

    @property
    @pulumi.getter(name="burnRateAlertEnabled")
    def burn_rate_alert_enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether burn rate alerts are enabled.
        """
        return pulumi.get(self, "burn_rate_alert_enabled")

    @burn_rate_alert_enabled.setter
    def burn_rate_alert_enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "burn_rate_alert_enabled", value)

    @property
    @pulumi.getter(name="burnRateThreshold")
    def burn_rate_threshold(self) -> Optional[pulumi.Input[float]]:
        """
        Burn rate threshold for alerts.
        """
        return pulumi.get(self, "burn_rate_threshold")

    @burn_rate_threshold.setter
    def burn_rate_threshold(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "burn_rate_threshold", value)

    @property
    @pulumi.getter(name="burnRateWindowMinutes")
    def burn_rate_window_minutes(self) -> Optional[pulumi.Input[int]]:
        """
        Burn rate evaluation window in minutes.
        """
        return pulumi.get(self, "burn_rate_window_minutes")

    @burn_rate_window_minutes.setter
    def burn_rate_window_minutes(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "burn_rate_window_minutes", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the SLO is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter(name="latencyThresholdMs")
    def latency_threshold_ms(self) -> Optional[pulumi.Input[int]]:
        """
        Latency threshold in milliseconds for latency-based SLIs.
        """
        return pulumi.get(self, "latency_threshold_ms")

    @latency_threshold_ms.setter
    def latency_threshold_ms(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "latency_threshold_ms", value)

    @property
    @pulumi.getter(name="notifyOnBudgetExhausted")
    def notify_on_budget_exhausted(self) -> Optional[pulumi.Input[bool]]:
        """
        Send notification when error budget is exhausted.
        """
        return pulumi.get(self, "notify_on_budget_exhausted")

    @notify_on_budget_exhausted.setter
    def notify_on_budget_exhausted(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify_on_budget_exhausted", value)

    @property
    @pulumi.getter(name="notifyOnBudgetWarn")
    def notify_on_budget_warn(self) -> Optional[pulumi.Input[bool]]:
        """
        Send notification when error budget reaches warning threshold.
        """
        return pulumi.get(self, "notify_on_budget_warn")

    @notify_on_budget_warn.setter
    def notify_on_budget_warn(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify_on_budget_warn", value)

    @property
    @pulumi.getter(name="sliType")
    def sli_type(self) -> Optional[pulumi.Input[str]]:
        """
        The SLI type. Currently only 'availability' is supported.
        """
        return pulumi.get(self, "sli_type")

    @sli_type.setter
    def sli_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "sli_type", value)

    @property
    @pulumi.getter(name="targetPercentage")
    def target_percentage(self) -> Optional[pulumi.Input[float]]:
        """
        The SLO target percentage (90.0 - 100.0).
        """
        return pulumi.get(self, "target_percentage")

    @target_percentage.setter
    def target_percentage(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "target_percentage", value)

    @property
    @pulumi.getter(name="windowDays")
    def window_days(self) -> Optional[pulumi.Input[int]]:
        """
        The SLO window in days (7, 30, or 90).
        """
        return pulumi.get(self, "window_days")

    @window_days.setter
    def window_days(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "window_days", value)


@pulumi.input_type
class _CheckSloState:
    def __init__(__self__, *,
                 budget_warn_pct: Optional[pulumi.Input[float]] = None,
                 burn_rate_alert_enabled: Optional[pulumi.Input[bool]] = None,
                 burn_rate_threshold: Optional[pulumi.Input[float]] = None,
                 burn_rate_window_minutes: Optional[pulumi.Input[int]] = None,
                 check_id: Optional[pulumi.Input[int]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 latency_threshold_ms: Optional[pulumi.Input[int]] = None,
                 notify_on_budget_exhausted: Optional[pulumi.Input[bool]] = None,
                 notify_on_budget_warn: Optional[pulumi.Input[bool]] = None,
                 sli_type: Optional[pulumi.Input[str]] = None,
                 target_percentage: Optional[pulumi.Input[float]] = None,
                 window_days: Optional[pulumi.Input[int]] = None):
        """
        Input properties used for looking up and filtering CheckSlo resources.
        :param pulumi.Input[float] budget_warn_pct: Error budget warning threshold percentage.
        :param pulumi.Input[bool] burn_rate_alert_enabled: Whether burn rate alerts are enabled.
        :param pulumi.Input[float] burn_rate_threshold: Burn rate threshold for alerts.
        :param pulumi.Input[int] burn_rate_window_minutes: Burn rate evaluation window in minutes.
        :param pulumi.Input[int] check_id: The ID of the check this SLO belongs to.
        :param pulumi.Input[bool] is_active: Whether the SLO is active.
        :param pulumi.Input[int] latency_threshold_ms: Latency threshold in milliseconds for latency-based SLIs.
        :param pulumi.Input[bool] notify_on_budget_exhausted: Send notification when error budget is exhausted.
        :param pulumi.Input[bool] notify_on_budget_warn: Send notification when error budget reaches warning threshold.
        :param pulumi.Input[str] sli_type: The SLI type. Currently only 'availability' is supported.
        :param pulumi.Input[float] target_percentage: The SLO target percentage (90.0 - 100.0).
        :param pulumi.Input[int] window_days: The SLO window in days (7, 30, or 90).
        """
        if budget_warn_pct is not None:
            pulumi.set(__self__, "budget_warn_pct", budget_warn_pct)
        if burn_rate_alert_enabled is not None:
            pulumi.set(__self__, "burn_rate_alert_enabled", burn_rate_alert_enabled)
        if burn_rate_threshold is not None:
            pulumi.set(__self__, "burn_rate_threshold", burn_rate_threshold)
        if burn_rate_window_minutes is not None:
            pulumi.set(__self__, "burn_rate_window_minutes", burn_rate_window_minutes)
        if check_id is not None:
            pulumi.set(__self__, "check_id", check_id)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if latency_threshold_ms is not None:
            pulumi.set(__self__, "latency_threshold_ms", latency_threshold_ms)
        if notify_on_budget_exhausted is not None:
            pulumi.set(__self__, "notify_on_budget_exhausted", notify_on_budget_exhausted)
        if notify_on_budget_warn is not None:
            pulumi.set(__self__, "notify_on_budget_warn", notify_on_budget_warn)
        if sli_type is not None:
            pulumi.set(__self__, "sli_type", sli_type)
        if target_percentage is not None:
            pulumi.set(__self__, "target_percentage", target_percentage)
        if window_days is not None:
            pulumi.set(__self__, "window_days", window_days)

    @property
    @pulumi.getter(name="budgetWarnPct")
    def budget_warn_pct(self) -> Optional[pulumi.Input[float]]:
        """
        Error budget warning threshold percentage.
        """
        return pulumi.get(self, "budget_warn_pct")

    @budget_warn_pct.setter
    def budget_warn_pct(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "budget_warn_pct", value)

    @property
    @pulumi.getter(name="burnRateAlertEnabled")
    def burn_rate_alert_enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether burn rate alerts are enabled.
        """
        return pulumi.get(self, "burn_rate_alert_enabled")

    @burn_rate_alert_enabled.setter
    def burn_rate_alert_enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "burn_rate_alert_enabled", value)

    @property
    @pulumi.getter(name="burnRateThreshold")
    def burn_rate_threshold(self) -> Optional[pulumi.Input[float]]:
        """
        Burn rate threshold for alerts.
        """
        return pulumi.get(self, "burn_rate_threshold")

    @burn_rate_threshold.setter
    def burn_rate_threshold(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "burn_rate_threshold", value)

    @property
    @pulumi.getter(name="burnRateWindowMinutes")
    def burn_rate_window_minutes(self) -> Optional[pulumi.Input[int]]:
        """
        Burn rate evaluation window in minutes.
        """
        return pulumi.get(self, "burn_rate_window_minutes")

    @burn_rate_window_minutes.setter
    def burn_rate_window_minutes(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "burn_rate_window_minutes", value)

    @property
    @pulumi.getter(name="checkId")
    def check_id(self) -> Optional[pulumi.Input[int]]:
        """
        The ID of the check this SLO belongs to.
        """
        return pulumi.get(self, "check_id")

    @check_id.setter
    def check_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "check_id", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the SLO is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter(name="latencyThresholdMs")
    def latency_threshold_ms(self) -> Optional[pulumi.Input[int]]:
        """
        Latency threshold in milliseconds for latency-based SLIs.
        """
        return pulumi.get(self, "latency_threshold_ms")

    @latency_threshold_ms.setter
    def latency_threshold_ms(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "latency_threshold_ms", value)

    @property
    @pulumi.getter(name="notifyOnBudgetExhausted")
    def notify_on_budget_exhausted(self) -> Optional[pulumi.Input[bool]]:
        """
        Send notification when error budget is exhausted.
        """
        return pulumi.get(self, "notify_on_budget_exhausted")

    @notify_on_budget_exhausted.setter
    def notify_on_budget_exhausted(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify_on_budget_exhausted", value)

    @property
    @pulumi.getter(name="notifyOnBudgetWarn")
    def notify_on_budget_warn(self) -> Optional[pulumi.Input[bool]]:
        """
        Send notification when error budget reaches warning threshold.
        """
        return pulumi.get(self, "notify_on_budget_warn")

    @notify_on_budget_warn.setter
    def notify_on_budget_warn(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify_on_budget_warn", value)

    @property
    @pulumi.getter(name="sliType")
    def sli_type(self) -> Optional[pulumi.Input[str]]:
        """
        The SLI type. Currently only 'availability' is supported.
        """
        return pulumi.get(self, "sli_type")

    @sli_type.setter
    def sli_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "sli_type", value)

    @property
    @pulumi.getter(name="targetPercentage")
    def target_percentage(self) -> Optional[pulumi.Input[float]]:
        """
        The SLO target percentage (90.0 - 100.0).
        """
        return pulumi.get(self, "target_percentage")

    @target_percentage.setter
    def target_percentage(self, value: Optional[pulumi.Input[float]]):
        pulumi.set(self, "target_percentage", value)

    @property
    @pulumi.getter(name="windowDays")
    def window_days(self) -> Optional[pulumi.Input[int]]:
        """
        The SLO window in days (7, 30, or 90).
        """
        return pulumi.get(self, "window_days")

    @window_days.setter
    def window_days(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "window_days", value)


class CheckSlo(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 budget_warn_pct: Optional[pulumi.Input[float]] = None,
                 burn_rate_alert_enabled: Optional[pulumi.Input[bool]] = None,
                 burn_rate_threshold: Optional[pulumi.Input[float]] = None,
                 burn_rate_window_minutes: Optional[pulumi.Input[int]] = None,
                 check_id: Optional[pulumi.Input[int]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 latency_threshold_ms: Optional[pulumi.Input[int]] = None,
                 notify_on_budget_exhausted: Optional[pulumi.Input[bool]] = None,
                 notify_on_budget_warn: Optional[pulumi.Input[bool]] = None,
                 sli_type: Optional[pulumi.Input[str]] = None,
                 target_percentage: Optional[pulumi.Input[float]] = None,
                 window_days: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        """
        Manages an SLO (Service Level Objective) for a check. One SLO per check.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[float] budget_warn_pct: Error budget warning threshold percentage.
        :param pulumi.Input[bool] burn_rate_alert_enabled: Whether burn rate alerts are enabled.
        :param pulumi.Input[float] burn_rate_threshold: Burn rate threshold for alerts.
        :param pulumi.Input[int] burn_rate_window_minutes: Burn rate evaluation window in minutes.
        :param pulumi.Input[int] check_id: The ID of the check this SLO belongs to.
        :param pulumi.Input[bool] is_active: Whether the SLO is active.
        :param pulumi.Input[int] latency_threshold_ms: Latency threshold in milliseconds for latency-based SLIs.
        :param pulumi.Input[bool] notify_on_budget_exhausted: Send notification when error budget is exhausted.
        :param pulumi.Input[bool] notify_on_budget_warn: Send notification when error budget reaches warning threshold.
        :param pulumi.Input[str] sli_type: The SLI type. Currently only 'availability' is supported.
        :param pulumi.Input[float] target_percentage: The SLO target percentage (90.0 - 100.0).
        :param pulumi.Input[int] window_days: The SLO window in days (7, 30, or 90).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CheckSloArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an SLO (Service Level Objective) for a check. One SLO per check.

        :param str resource_name: The name of the resource.
        :param CheckSloArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CheckSloArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 budget_warn_pct: Optional[pulumi.Input[float]] = None,
                 burn_rate_alert_enabled: Optional[pulumi.Input[bool]] = None,
                 burn_rate_threshold: Optional[pulumi.Input[float]] = None,
                 burn_rate_window_minutes: Optional[pulumi.Input[int]] = None,
                 check_id: Optional[pulumi.Input[int]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 latency_threshold_ms: Optional[pulumi.Input[int]] = None,
                 notify_on_budget_exhausted: Optional[pulumi.Input[bool]] = None,
                 notify_on_budget_warn: Optional[pulumi.Input[bool]] = None,
                 sli_type: Optional[pulumi.Input[str]] = None,
                 target_percentage: Optional[pulumi.Input[float]] = None,
                 window_days: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CheckSloArgs.__new__(CheckSloArgs)

            __props__.__dict__["budget_warn_pct"] = budget_warn_pct
            __props__.__dict__["burn_rate_alert_enabled"] = burn_rate_alert_enabled
            __props__.__dict__["burn_rate_threshold"] = burn_rate_threshold
            __props__.__dict__["burn_rate_window_minutes"] = burn_rate_window_minutes
            if check_id is None and not opts.urn:
                raise TypeError("Missing required property 'check_id'")
            __props__.__dict__["check_id"] = check_id
            __props__.__dict__["is_active"] = is_active
            __props__.__dict__["latency_threshold_ms"] = latency_threshold_ms
            __props__.__dict__["notify_on_budget_exhausted"] = notify_on_budget_exhausted
            __props__.__dict__["notify_on_budget_warn"] = notify_on_budget_warn
            __props__.__dict__["sli_type"] = sli_type
            __props__.__dict__["target_percentage"] = target_percentage
            __props__.__dict__["window_days"] = window_days
        super(CheckSlo, __self__).__init__(
            'systeam:index/checkSlo:CheckSlo',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            budget_warn_pct: Optional[pulumi.Input[float]] = None,
            burn_rate_alert_enabled: Optional[pulumi.Input[bool]] = None,
            burn_rate_threshold: Optional[pulumi.Input[float]] = None,
            burn_rate_window_minutes: Optional[pulumi.Input[int]] = None,
            check_id: Optional[pulumi.Input[int]] = None,
            is_active: Optional[pulumi.Input[bool]] = None,
            latency_threshold_ms: Optional[pulumi.Input[int]] = None,
            notify_on_budget_exhausted: Optional[pulumi.Input[bool]] = None,
            notify_on_budget_warn: Optional[pulumi.Input[bool]] = None,
            sli_type: Optional[pulumi.Input[str]] = None,
            target_percentage: Optional[pulumi.Input[float]] = None,
            window_days: Optional[pulumi.Input[int]] = None) -> 'CheckSlo':
        """
        Get an existing CheckSlo resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[float] budget_warn_pct: Error budget warning threshold percentage.
        :param pulumi.Input[bool] burn_rate_alert_enabled: Whether burn rate alerts are enabled.
        :param pulumi.Input[float] burn_rate_threshold: Burn rate threshold for alerts.
        :param pulumi.Input[int] burn_rate_window_minutes: Burn rate evaluation window in minutes.
        :param pulumi.Input[int] check_id: The ID of the check this SLO belongs to.
        :param pulumi.Input[bool] is_active: Whether the SLO is active.
        :param pulumi.Input[int] latency_threshold_ms: Latency threshold in milliseconds for latency-based SLIs.
        :param pulumi.Input[bool] notify_on_budget_exhausted: Send notification when error budget is exhausted.
        :param pulumi.Input[bool] notify_on_budget_warn: Send notification when error budget reaches warning threshold.
        :param pulumi.Input[str] sli_type: The SLI type. Currently only 'availability' is supported.
        :param pulumi.Input[float] target_percentage: The SLO target percentage (90.0 - 100.0).
        :param pulumi.Input[int] window_days: The SLO window in days (7, 30, or 90).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CheckSloState.__new__(_CheckSloState)

        __props__.__dict__["budget_warn_pct"] = budget_warn_pct
        __props__.__dict__["burn_rate_alert_enabled"] = burn_rate_alert_enabled
        __props__.__dict__["burn_rate_threshold"] = burn_rate_threshold
        __props__.__dict__["burn_rate_window_minutes"] = burn_rate_window_minutes
        __props__.__dict__["check_id"] = check_id
        __props__.__dict__["is_active"] = is_active
        __props__.__dict__["latency_threshold_ms"] = latency_threshold_ms
        __props__.__dict__["notify_on_budget_exhausted"] = notify_on_budget_exhausted
        __props__.__dict__["notify_on_budget_warn"] = notify_on_budget_warn
        __props__.__dict__["sli_type"] = sli_type
        __props__.__dict__["target_percentage"] = target_percentage
        __props__.__dict__["window_days"] = window_days
        return CheckSlo(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="budgetWarnPct")
    def budget_warn_pct(self) -> pulumi.Output[float]:
        """
        Error budget warning threshold percentage.
        """
        return pulumi.get(self, "budget_warn_pct")

    @property
    @pulumi.getter(name="burnRateAlertEnabled")
    def burn_rate_alert_enabled(self) -> pulumi.Output[bool]:
        """
        Whether burn rate alerts are enabled.
        """
        return pulumi.get(self, "burn_rate_alert_enabled")

    @property
    @pulumi.getter(name="burnRateThreshold")
    def burn_rate_threshold(self) -> pulumi.Output[float]:
        """
        Burn rate threshold for alerts.
        """
        return pulumi.get(self, "burn_rate_threshold")

    @property
    @pulumi.getter(name="burnRateWindowMinutes")
    def burn_rate_window_minutes(self) -> pulumi.Output[int]:
        """
        Burn rate evaluation window in minutes.
        """
        return pulumi.get(self, "burn_rate_window_minutes")

    @property
    @pulumi.getter(name="checkId")
    def check_id(self) -> pulumi.Output[int]:
        """
        The ID of the check this SLO belongs to.
        """
        return pulumi.get(self, "check_id")

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[bool]:
        """
        Whether the SLO is active.
        """
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter(name="latencyThresholdMs")
    def latency_threshold_ms(self) -> pulumi.Output[Optional[int]]:
        """
        Latency threshold in milliseconds for latency-based SLIs.
        """
        return pulumi.get(self, "latency_threshold_ms")

    @property
    @pulumi.getter(name="notifyOnBudgetExhausted")
    def notify_on_budget_exhausted(self) -> pulumi.Output[bool]:
        """
        Send notification when error budget is exhausted.
        """
        return pulumi.get(self, "notify_on_budget_exhausted")

    @property
    @pulumi.getter(name="notifyOnBudgetWarn")
    def notify_on_budget_warn(self) -> pulumi.Output[bool]:
        """
        Send notification when error budget reaches warning threshold.
        """
        return pulumi.get(self, "notify_on_budget_warn")

    @property
    @pulumi.getter(name="sliType")
    def sli_type(self) -> pulumi.Output[str]:
        """
        The SLI type. Currently only 'availability' is supported.
        """
        return pulumi.get(self, "sli_type")

    @property
    @pulumi.getter(name="targetPercentage")
    def target_percentage(self) -> pulumi.Output[float]:
        """
        The SLO target percentage (90.0 - 100.0).
        """
        return pulumi.get(self, "target_percentage")

    @property
    @pulumi.getter(name="windowDays")
    def window_days(self) -> pulumi.Output[int]:
        """
        The SLO window in days (7, 30, or 90).
        """
        return pulumi.get(self, "window_days")

