# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ContactMethodArgs', 'ContactMethod']

@pulumi.input_type
class ContactMethodArgs:
    def __init__(__self__, *,
                 kind: pulumi.Input[str],
                 enabled: Optional[pulumi.Input[bool]] = None,
                 label: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a ContactMethod resource.
        :param pulumi.Input[str] kind: Contact channel: sms, voice, email, or push.
        :param pulumi.Input[bool] enabled: Whether the method is enabled for notifications.
        :param pulumi.Input[str] label: A human-readable label.
        :param pulumi.Input[str] value: The phone number (sms/voice) or email address (email). Omit for push.
        """
        pulumi.set(__self__, "kind", kind)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if label is not None:
            pulumi.set(__self__, "label", label)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def kind(self) -> pulumi.Input[str]:
        """
        Contact channel: sms, voice, email, or push.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[str]):
        pulumi.set(self, "kind", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the method is enabled for notifications.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter
    def label(self) -> Optional[pulumi.Input[str]]:
        """
        A human-readable label.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "label", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[str]]:
        """
        The phone number (sms/voice) or email address (email). Omit for push.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "value", value)


@pulumi.input_type
class _ContactMethodState:
    def __init__(__self__, *,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 label: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None,
                 verified: Optional[pulumi.Input[bool]] = None):
        """
        Input properties used for looking up and filtering ContactMethod resources.
        :param pulumi.Input[bool] enabled: Whether the method is enabled for notifications.
        :param pulumi.Input[str] kind: Contact channel: sms, voice, email, or push.
        :param pulumi.Input[str] label: A human-readable label.
        :param pulumi.Input[str] value: The phone number (sms/voice) or email address (email). Omit for push.
        :param pulumi.Input[bool] verified: Whether the method has been verified (read-only; verify out of band).
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if label is not None:
            pulumi.set(__self__, "label", label)
        if value is not None:
            pulumi.set(__self__, "value", value)
        if verified is not None:
            pulumi.set(__self__, "verified", verified)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the method is enabled for notifications.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter
    def kind(self) -> Optional[pulumi.Input[str]]:
        """
        Contact channel: sms, voice, email, or push.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "kind", value)

    @property
    @pulumi.getter
    def label(self) -> Optional[pulumi.Input[str]]:
        """
        A human-readable label.
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "label", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[str]]:
        """
        The phone number (sms/voice) or email address (email). Omit for push.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "value", value)

    @property
    @pulumi.getter
    def verified(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the method has been verified (read-only; verify out of band).
        """
        return pulumi.get(self, "verified")

    @verified.setter
    def verified(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "verified", value)


class ContactMethod(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 label: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Manages a per-user contact method (phone/email/push) used by on-call escalation. Tied to the provider token's user. Verification happens out of band (a code is sent to the target) and cannot be automated — a freshly created method starts unverified.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] enabled: Whether the method is enabled for notifications.
        :param pulumi.Input[str] kind: Contact channel: sms, voice, email, or push.
        :param pulumi.Input[str] label: A human-readable label.
        :param pulumi.Input[str] value: The phone number (sms/voice) or email address (email). Omit for push.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ContactMethodArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a per-user contact method (phone/email/push) used by on-call escalation. Tied to the provider token's user. Verification happens out of band (a code is sent to the target) and cannot be automated — a freshly created method starts unverified.

        :param str resource_name: The name of the resource.
        :param ContactMethodArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ContactMethodArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 label: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ContactMethodArgs.__new__(ContactMethodArgs)

            __props__.__dict__["enabled"] = enabled
            if kind is None and not opts.urn:
                raise TypeError("Missing required property 'kind'")
            __props__.__dict__["kind"] = kind
            __props__.__dict__["label"] = label
            __props__.__dict__["value"] = value
            __props__.__dict__["verified"] = None
        super(ContactMethod, __self__).__init__(
            'systeam:index/contactMethod:ContactMethod',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            enabled: Optional[pulumi.Input[bool]] = None,
            kind: Optional[pulumi.Input[str]] = None,
            label: Optional[pulumi.Input[str]] = None,
            value: Optional[pulumi.Input[str]] = None,
            verified: Optional[pulumi.Input[bool]] = None) -> 'ContactMethod':
        """
        Get an existing ContactMethod resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] enabled: Whether the method is enabled for notifications.
        :param pulumi.Input[str] kind: Contact channel: sms, voice, email, or push.
        :param pulumi.Input[str] label: A human-readable label.
        :param pulumi.Input[str] value: The phone number (sms/voice) or email address (email). Omit for push.
        :param pulumi.Input[bool] verified: Whether the method has been verified (read-only; verify out of band).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ContactMethodState.__new__(_ContactMethodState)

        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["kind"] = kind
        __props__.__dict__["label"] = label
        __props__.__dict__["value"] = value
        __props__.__dict__["verified"] = verified
        return ContactMethod(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[bool]:
        """
        Whether the method is enabled for notifications.
        """
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter
    def kind(self) -> pulumi.Output[str]:
        """
        Contact channel: sms, voice, email, or push.
        """
        return pulumi.get(self, "kind")

    @property
    @pulumi.getter
    def label(self) -> pulumi.Output[str]:
        """
        A human-readable label.
        """
        return pulumi.get(self, "label")

    @property
    @pulumi.getter
    def value(self) -> pulumi.Output[Optional[str]]:
        """
        The phone number (sms/voice) or email address (email). Omit for push.
        """
        return pulumi.get(self, "value")

    @property
    @pulumi.getter
    def verified(self) -> pulumi.Output[bool]:
        """
        Whether the method has been verified (read-only; verify out of band).
        """
        return pulumi.get(self, "verified")

