# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['EscalationPolicyArgs', 'EscalationPolicy']

@pulumi.input_type
class EscalationPolicyArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 organization_id: pulumi.Input[int],
                 is_active: Optional[pulumi.Input[bool]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]]] = None):
        """
        The set of arguments for constructing a EscalationPolicy resource.
        :param pulumi.Input[str] name: The name of the escalation policy.
        :param pulumi.Input[int] organization_id: The ID of the organization this policy belongs to.
        :param pulumi.Input[bool] is_active: Whether the escalation policy is active.
        :param pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]] steps: Ordered escalation steps.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "organization_id", organization_id)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        The name of the escalation policy.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[int]:
        """
        The ID of the organization this policy belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the escalation policy is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter
    def steps(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]]]:
        """
        Ordered escalation steps.
        """
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]]]):
        pulumi.set(self, "steps", value)


@pulumi.input_type
class _EscalationPolicyState:
    def __init__(__self__, *,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]]] = None):
        """
        Input properties used for looking up and filtering EscalationPolicy resources.
        :param pulumi.Input[bool] is_active: Whether the escalation policy is active.
        :param pulumi.Input[str] name: The name of the escalation policy.
        :param pulumi.Input[int] organization_id: The ID of the organization this policy belongs to.
        :param pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]] steps: Ordered escalation steps.
        """
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the escalation policy is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the escalation policy.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[int]]:
        """
        The ID of the organization this policy belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def steps(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]]]:
        """
        Ordered escalation steps.
        """
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['EscalationPolicyStepArgs']]]]):
        pulumi.set(self, "steps", value)


class EscalationPolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input[Union['EscalationPolicyStepArgs', 'EscalationPolicyStepArgsDict']]]]] = None,
                 __props__=None):
        """
        Manages an escalation policy with ordered steps.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] is_active: Whether the escalation policy is active.
        :param pulumi.Input[str] name: The name of the escalation policy.
        :param pulumi.Input[int] organization_id: The ID of the organization this policy belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[Union['EscalationPolicyStepArgs', 'EscalationPolicyStepArgsDict']]]] steps: Ordered escalation steps.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EscalationPolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an escalation policy with ordered steps.

        :param str resource_name: The name of the resource.
        :param EscalationPolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EscalationPolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input[Union['EscalationPolicyStepArgs', 'EscalationPolicyStepArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EscalationPolicyArgs.__new__(EscalationPolicyArgs)

            __props__.__dict__["is_active"] = is_active
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["steps"] = steps
        super(EscalationPolicy, __self__).__init__(
            'systeam:index/escalationPolicy:EscalationPolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            is_active: Optional[pulumi.Input[bool]] = None,
            name: Optional[pulumi.Input[str]] = None,
            organization_id: Optional[pulumi.Input[int]] = None,
            steps: Optional[pulumi.Input[Sequence[pulumi.Input[Union['EscalationPolicyStepArgs', 'EscalationPolicyStepArgsDict']]]]] = None) -> 'EscalationPolicy':
        """
        Get an existing EscalationPolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] is_active: Whether the escalation policy is active.
        :param pulumi.Input[str] name: The name of the escalation policy.
        :param pulumi.Input[int] organization_id: The ID of the organization this policy belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[Union['EscalationPolicyStepArgs', 'EscalationPolicyStepArgsDict']]]] steps: Ordered escalation steps.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _EscalationPolicyState.__new__(_EscalationPolicyState)

        __props__.__dict__["is_active"] = is_active
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["steps"] = steps
        return EscalationPolicy(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[bool]:
        """
        Whether the escalation policy is active.
        """
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The name of the escalation policy.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[int]:
        """
        The ID of the organization this policy belongs to.
        """
        return pulumi.get(self, "organization_id")

    @property
    @pulumi.getter
    def steps(self) -> pulumi.Output[Optional[Sequence['outputs.EscalationPolicyStep']]]:
        """
        Ordered escalation steps.
        """
        return pulumi.get(self, "steps")

