# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['IntegrationKeyArgs', 'IntegrationKey']

@pulumi.input_type
class IntegrationKeyArgs:
    def __init__(__self__, *,
                 escalation_policy_id: pulumi.Input[int],
                 name: pulumi.Input[str],
                 organization_id: pulumi.Input[int],
                 grouping_type: Optional[pulumi.Input[str]] = None,
                 grouping_window_seconds: Optional[pulumi.Input[int]] = None):
        """
        The set of arguments for constructing a IntegrationKey resource.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy that inbound events on this key are routed to.
        :param pulumi.Input[str] name: A human-readable name for the key.
        :param pulumi.Input[int] organization_id: The ID of the organization this key belongs to.
        :param pulumi.Input[str] grouping_type: How incoming alerts are grouped into incidents: none, time_window, service, or intelligent.
        :param pulumi.Input[int] grouping_window_seconds: The grouping window in seconds (used when grouping_type is not 'none').
        """
        pulumi.set(__self__, "escalation_policy_id", escalation_policy_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "organization_id", organization_id)
        if grouping_type is not None:
            pulumi.set(__self__, "grouping_type", grouping_type)
        if grouping_window_seconds is not None:
            pulumi.set(__self__, "grouping_window_seconds", grouping_window_seconds)

    @property
    @pulumi.getter(name="escalationPolicyId")
    def escalation_policy_id(self) -> pulumi.Input[int]:
        """
        The escalation policy that inbound events on this key are routed to.
        """
        return pulumi.get(self, "escalation_policy_id")

    @escalation_policy_id.setter
    def escalation_policy_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "escalation_policy_id", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        A human-readable name for the key.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[int]:
        """
        The ID of the organization this key belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter(name="groupingType")
    def grouping_type(self) -> Optional[pulumi.Input[str]]:
        """
        How incoming alerts are grouped into incidents: none, time_window, service, or intelligent.
        """
        return pulumi.get(self, "grouping_type")

    @grouping_type.setter
    def grouping_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "grouping_type", value)

    @property
    @pulumi.getter(name="groupingWindowSeconds")
    def grouping_window_seconds(self) -> Optional[pulumi.Input[int]]:
        """
        The grouping window in seconds (used when grouping_type is not 'none').
        """
        return pulumi.get(self, "grouping_window_seconds")

    @grouping_window_seconds.setter
    def grouping_window_seconds(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "grouping_window_seconds", value)


@pulumi.input_type
class _IntegrationKeyState:
    def __init__(__self__, *,
                 escalation_policy_id: Optional[pulumi.Input[int]] = None,
                 grouping_type: Optional[pulumi.Input[str]] = None,
                 grouping_window_seconds: Optional[pulumi.Input[int]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 token: Optional[pulumi.Input[str]] = None,
                 token_prefix: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering IntegrationKey resources.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy that inbound events on this key are routed to.
        :param pulumi.Input[str] grouping_type: How incoming alerts are grouped into incidents: none, time_window, service, or intelligent.
        :param pulumi.Input[int] grouping_window_seconds: The grouping window in seconds (used when grouping_type is not 'none').
        :param pulumi.Input[bool] is_active: Whether the key is active (revoked keys are inactive).
        :param pulumi.Input[str] name: A human-readable name for the key.
        :param pulumi.Input[int] organization_id: The ID of the organization this key belongs to.
        :param pulumi.Input[str] token: The full secret routing key. Returned ONLY at creation; put it in your Alertmanager/Grafana webhook URL. It is not readable afterwards, so it is preserved in state from the create.
        :param pulumi.Input[str] token_prefix: The non-secret prefix of the key, shown in the UI to identify it.
        """
        if escalation_policy_id is not None:
            pulumi.set(__self__, "escalation_policy_id", escalation_policy_id)
        if grouping_type is not None:
            pulumi.set(__self__, "grouping_type", grouping_type)
        if grouping_window_seconds is not None:
            pulumi.set(__self__, "grouping_window_seconds", grouping_window_seconds)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if token is not None:
            pulumi.set(__self__, "token", token)
        if token_prefix is not None:
            pulumi.set(__self__, "token_prefix", token_prefix)

    @property
    @pulumi.getter(name="escalationPolicyId")
    def escalation_policy_id(self) -> Optional[pulumi.Input[int]]:
        """
        The escalation policy that inbound events on this key are routed to.
        """
        return pulumi.get(self, "escalation_policy_id")

    @escalation_policy_id.setter
    def escalation_policy_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "escalation_policy_id", value)

    @property
    @pulumi.getter(name="groupingType")
    def grouping_type(self) -> Optional[pulumi.Input[str]]:
        """
        How incoming alerts are grouped into incidents: none, time_window, service, or intelligent.
        """
        return pulumi.get(self, "grouping_type")

    @grouping_type.setter
    def grouping_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "grouping_type", value)

    @property
    @pulumi.getter(name="groupingWindowSeconds")
    def grouping_window_seconds(self) -> Optional[pulumi.Input[int]]:
        """
        The grouping window in seconds (used when grouping_type is not 'none').
        """
        return pulumi.get(self, "grouping_window_seconds")

    @grouping_window_seconds.setter
    def grouping_window_seconds(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "grouping_window_seconds", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the key is active (revoked keys are inactive).
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        A human-readable name for the key.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[int]]:
        """
        The ID of the organization this key belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[str]]:
        """
        The full secret routing key. Returned ONLY at creation; put it in your Alertmanager/Grafana webhook URL. It is not readable afterwards, so it is preserved in state from the create.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "token", value)

    @property
    @pulumi.getter(name="tokenPrefix")
    def token_prefix(self) -> Optional[pulumi.Input[str]]:
        """
        The non-secret prefix of the key, shown in the UI to identify it.
        """
        return pulumi.get(self, "token_prefix")

    @token_prefix.setter
    def token_prefix(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "token_prefix", value)


class IntegrationKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 escalation_policy_id: Optional[pulumi.Input[int]] = None,
                 grouping_type: Optional[pulumi.Input[str]] = None,
                 grouping_window_seconds: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        """
        Manages an inbound-events integration key. External systems (Alertmanager, Grafana, Prometheus, PagerDuty-format senders) authenticate with this key to raise incidents that route to an escalation policy.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy that inbound events on this key are routed to.
        :param pulumi.Input[str] grouping_type: How incoming alerts are grouped into incidents: none, time_window, service, or intelligent.
        :param pulumi.Input[int] grouping_window_seconds: The grouping window in seconds (used when grouping_type is not 'none').
        :param pulumi.Input[str] name: A human-readable name for the key.
        :param pulumi.Input[int] organization_id: The ID of the organization this key belongs to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IntegrationKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an inbound-events integration key. External systems (Alertmanager, Grafana, Prometheus, PagerDuty-format senders) authenticate with this key to raise incidents that route to an escalation policy.

        :param str resource_name: The name of the resource.
        :param IntegrationKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IntegrationKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 escalation_policy_id: Optional[pulumi.Input[int]] = None,
                 grouping_type: Optional[pulumi.Input[str]] = None,
                 grouping_window_seconds: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IntegrationKeyArgs.__new__(IntegrationKeyArgs)

            if escalation_policy_id is None and not opts.urn:
                raise TypeError("Missing required property 'escalation_policy_id'")
            __props__.__dict__["escalation_policy_id"] = escalation_policy_id
            __props__.__dict__["grouping_type"] = grouping_type
            __props__.__dict__["grouping_window_seconds"] = grouping_window_seconds
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["is_active"] = None
            __props__.__dict__["token"] = None
            __props__.__dict__["token_prefix"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(IntegrationKey, __self__).__init__(
            'systeam:index/integrationKey:IntegrationKey',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            escalation_policy_id: Optional[pulumi.Input[int]] = None,
            grouping_type: Optional[pulumi.Input[str]] = None,
            grouping_window_seconds: Optional[pulumi.Input[int]] = None,
            is_active: Optional[pulumi.Input[bool]] = None,
            name: Optional[pulumi.Input[str]] = None,
            organization_id: Optional[pulumi.Input[int]] = None,
            token: Optional[pulumi.Input[str]] = None,
            token_prefix: Optional[pulumi.Input[str]] = None) -> 'IntegrationKey':
        """
        Get an existing IntegrationKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy that inbound events on this key are routed to.
        :param pulumi.Input[str] grouping_type: How incoming alerts are grouped into incidents: none, time_window, service, or intelligent.
        :param pulumi.Input[int] grouping_window_seconds: The grouping window in seconds (used when grouping_type is not 'none').
        :param pulumi.Input[bool] is_active: Whether the key is active (revoked keys are inactive).
        :param pulumi.Input[str] name: A human-readable name for the key.
        :param pulumi.Input[int] organization_id: The ID of the organization this key belongs to.
        :param pulumi.Input[str] token: The full secret routing key. Returned ONLY at creation; put it in your Alertmanager/Grafana webhook URL. It is not readable afterwards, so it is preserved in state from the create.
        :param pulumi.Input[str] token_prefix: The non-secret prefix of the key, shown in the UI to identify it.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IntegrationKeyState.__new__(_IntegrationKeyState)

        __props__.__dict__["escalation_policy_id"] = escalation_policy_id
        __props__.__dict__["grouping_type"] = grouping_type
        __props__.__dict__["grouping_window_seconds"] = grouping_window_seconds
        __props__.__dict__["is_active"] = is_active
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["token"] = token
        __props__.__dict__["token_prefix"] = token_prefix
        return IntegrationKey(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="escalationPolicyId")
    def escalation_policy_id(self) -> pulumi.Output[int]:
        """
        The escalation policy that inbound events on this key are routed to.
        """
        return pulumi.get(self, "escalation_policy_id")

    @property
    @pulumi.getter(name="groupingType")
    def grouping_type(self) -> pulumi.Output[str]:
        """
        How incoming alerts are grouped into incidents: none, time_window, service, or intelligent.
        """
        return pulumi.get(self, "grouping_type")

    @property
    @pulumi.getter(name="groupingWindowSeconds")
    def grouping_window_seconds(self) -> pulumi.Output[int]:
        """
        The grouping window in seconds (used when grouping_type is not 'none').
        """
        return pulumi.get(self, "grouping_window_seconds")

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[bool]:
        """
        Whether the key is active (revoked keys are inactive).
        """
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        A human-readable name for the key.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[int]:
        """
        The ID of the organization this key belongs to.
        """
        return pulumi.get(self, "organization_id")

    @property
    @pulumi.getter
    def token(self) -> pulumi.Output[str]:
        """
        The full secret routing key. Returned ONLY at creation; put it in your Alertmanager/Grafana webhook URL. It is not readable afterwards, so it is preserved in state from the create.
        """
        return pulumi.get(self, "token")

    @property
    @pulumi.getter(name="tokenPrefix")
    def token_prefix(self) -> pulumi.Output[str]:
        """
        The non-secret prefix of the key, shown in the UI to identify it.
        """
        return pulumi.get(self, "token_prefix")

