# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['LifecycleWatchArgs', 'LifecycleWatch']

@pulumi.input_type
class LifecycleWatchArgs:
    def __init__(__self__, *,
                 organization_id: pulumi.Input[int],
                 vendor: pulumi.Input[str],
                 channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 notify30d: Optional[pulumi.Input[bool]] = None,
                 notify7d: Optional[pulumi.Input[bool]] = None,
                 notify90d: Optional[pulumi.Input[bool]] = None,
                 notify_on_new: Optional[pulumi.Input[bool]] = None,
                 platform: Optional[pulumi.Input[str]] = None,
                 resource_id: Optional[pulumi.Input[str]] = None,
                 resource_type: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a LifecycleWatch resource.
        :param pulumi.Input[int] organization_id: The organization this watch belongs to.
        :param pulumi.Input[str] vendor: The vendor being watched (e.g. 'openai', 'anthropic').
        :param pulumi.Input[Sequence[pulumi.Input[int]]] channel_ids: Notification channels to alert. Write-only: the API does not return these on read.
        :param pulumi.Input[bool] notify30d: Notify 30 days before end-of-life.
        :param pulumi.Input[bool] notify7d: Notify 7 days before end-of-life.
        :param pulumi.Input[bool] notify90d: Notify 90 days before end-of-life.
        :param pulumi.Input[bool] notify_on_new: Notify when a new release/version appears.
        :param pulumi.Input[str] platform: Optional platform qualifier (part of the watch's identity).
        :param pulumi.Input[str] resource_id: Optional specific resource id to watch (part of the watch's identity).
        :param pulumi.Input[str] resource_type: The kind of resource being watched (default 'ai_model').
        """
        pulumi.set(__self__, "organization_id", organization_id)
        pulumi.set(__self__, "vendor", vendor)
        if channel_ids is not None:
            pulumi.set(__self__, "channel_ids", channel_ids)
        if notify30d is not None:
            pulumi.set(__self__, "notify30d", notify30d)
        if notify7d is not None:
            pulumi.set(__self__, "notify7d", notify7d)
        if notify90d is not None:
            pulumi.set(__self__, "notify90d", notify90d)
        if notify_on_new is not None:
            pulumi.set(__self__, "notify_on_new", notify_on_new)
        if platform is not None:
            pulumi.set(__self__, "platform", platform)
        if resource_id is not None:
            pulumi.set(__self__, "resource_id", resource_id)
        if resource_type is not None:
            pulumi.set(__self__, "resource_type", resource_type)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[int]:
        """
        The organization this watch belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def vendor(self) -> pulumi.Input[str]:
        """
        The vendor being watched (e.g. 'openai', 'anthropic').
        """
        return pulumi.get(self, "vendor")

    @vendor.setter
    def vendor(self, value: pulumi.Input[str]):
        pulumi.set(self, "vendor", value)

    @property
    @pulumi.getter(name="channelIds")
    def channel_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        """
        Notification channels to alert. Write-only: the API does not return these on read.
        """
        return pulumi.get(self, "channel_ids")

    @channel_ids.setter
    def channel_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "channel_ids", value)

    @property
    @pulumi.getter
    def notify30d(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify 30 days before end-of-life.
        """
        return pulumi.get(self, "notify30d")

    @notify30d.setter
    def notify30d(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify30d", value)

    @property
    @pulumi.getter
    def notify7d(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify 7 days before end-of-life.
        """
        return pulumi.get(self, "notify7d")

    @notify7d.setter
    def notify7d(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify7d", value)

    @property
    @pulumi.getter
    def notify90d(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify 90 days before end-of-life.
        """
        return pulumi.get(self, "notify90d")

    @notify90d.setter
    def notify90d(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify90d", value)

    @property
    @pulumi.getter(name="notifyOnNew")
    def notify_on_new(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify when a new release/version appears.
        """
        return pulumi.get(self, "notify_on_new")

    @notify_on_new.setter
    def notify_on_new(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify_on_new", value)

    @property
    @pulumi.getter
    def platform(self) -> Optional[pulumi.Input[str]]:
        """
        Optional platform qualifier (part of the watch's identity).
        """
        return pulumi.get(self, "platform")

    @platform.setter
    def platform(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "platform", value)

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> Optional[pulumi.Input[str]]:
        """
        Optional specific resource id to watch (part of the watch's identity).
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "resource_id", value)

    @property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> Optional[pulumi.Input[str]]:
        """
        The kind of resource being watched (default 'ai_model').
        """
        return pulumi.get(self, "resource_type")

    @resource_type.setter
    def resource_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "resource_type", value)


@pulumi.input_type
class _LifecycleWatchState:
    def __init__(__self__, *,
                 channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 notify30d: Optional[pulumi.Input[bool]] = None,
                 notify7d: Optional[pulumi.Input[bool]] = None,
                 notify90d: Optional[pulumi.Input[bool]] = None,
                 notify_on_new: Optional[pulumi.Input[bool]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 platform: Optional[pulumi.Input[str]] = None,
                 resource_id: Optional[pulumi.Input[str]] = None,
                 resource_type: Optional[pulumi.Input[str]] = None,
                 vendor: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering LifecycleWatch resources.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] channel_ids: Notification channels to alert. Write-only: the API does not return these on read.
        :param pulumi.Input[bool] notify30d: Notify 30 days before end-of-life.
        :param pulumi.Input[bool] notify7d: Notify 7 days before end-of-life.
        :param pulumi.Input[bool] notify90d: Notify 90 days before end-of-life.
        :param pulumi.Input[bool] notify_on_new: Notify when a new release/version appears.
        :param pulumi.Input[int] organization_id: The organization this watch belongs to.
        :param pulumi.Input[str] platform: Optional platform qualifier (part of the watch's identity).
        :param pulumi.Input[str] resource_id: Optional specific resource id to watch (part of the watch's identity).
        :param pulumi.Input[str] resource_type: The kind of resource being watched (default 'ai_model').
        :param pulumi.Input[str] vendor: The vendor being watched (e.g. 'openai', 'anthropic').
        """
        if channel_ids is not None:
            pulumi.set(__self__, "channel_ids", channel_ids)
        if notify30d is not None:
            pulumi.set(__self__, "notify30d", notify30d)
        if notify7d is not None:
            pulumi.set(__self__, "notify7d", notify7d)
        if notify90d is not None:
            pulumi.set(__self__, "notify90d", notify90d)
        if notify_on_new is not None:
            pulumi.set(__self__, "notify_on_new", notify_on_new)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if platform is not None:
            pulumi.set(__self__, "platform", platform)
        if resource_id is not None:
            pulumi.set(__self__, "resource_id", resource_id)
        if resource_type is not None:
            pulumi.set(__self__, "resource_type", resource_type)
        if vendor is not None:
            pulumi.set(__self__, "vendor", vendor)

    @property
    @pulumi.getter(name="channelIds")
    def channel_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        """
        Notification channels to alert. Write-only: the API does not return these on read.
        """
        return pulumi.get(self, "channel_ids")

    @channel_ids.setter
    def channel_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "channel_ids", value)

    @property
    @pulumi.getter
    def notify30d(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify 30 days before end-of-life.
        """
        return pulumi.get(self, "notify30d")

    @notify30d.setter
    def notify30d(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify30d", value)

    @property
    @pulumi.getter
    def notify7d(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify 7 days before end-of-life.
        """
        return pulumi.get(self, "notify7d")

    @notify7d.setter
    def notify7d(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify7d", value)

    @property
    @pulumi.getter
    def notify90d(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify 90 days before end-of-life.
        """
        return pulumi.get(self, "notify90d")

    @notify90d.setter
    def notify90d(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify90d", value)

    @property
    @pulumi.getter(name="notifyOnNew")
    def notify_on_new(self) -> Optional[pulumi.Input[bool]]:
        """
        Notify when a new release/version appears.
        """
        return pulumi.get(self, "notify_on_new")

    @notify_on_new.setter
    def notify_on_new(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "notify_on_new", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[int]]:
        """
        The organization this watch belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def platform(self) -> Optional[pulumi.Input[str]]:
        """
        Optional platform qualifier (part of the watch's identity).
        """
        return pulumi.get(self, "platform")

    @platform.setter
    def platform(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "platform", value)

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> Optional[pulumi.Input[str]]:
        """
        Optional specific resource id to watch (part of the watch's identity).
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "resource_id", value)

    @property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> Optional[pulumi.Input[str]]:
        """
        The kind of resource being watched (default 'ai_model').
        """
        return pulumi.get(self, "resource_type")

    @resource_type.setter
    def resource_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "resource_type", value)

    @property
    @pulumi.getter
    def vendor(self) -> Optional[pulumi.Input[str]]:
        """
        The vendor being watched (e.g. 'openai', 'anthropic').
        """
        return pulumi.get(self, "vendor")

    @vendor.setter
    def vendor(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "vendor", value)


class LifecycleWatch(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 notify30d: Optional[pulumi.Input[bool]] = None,
                 notify7d: Optional[pulumi.Input[bool]] = None,
                 notify90d: Optional[pulumi.Input[bool]] = None,
                 notify_on_new: Optional[pulumi.Input[bool]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 platform: Optional[pulumi.Input[str]] = None,
                 resource_id: Optional[pulumi.Input[str]] = None,
                 resource_type: Optional[pulumi.Input[str]] = None,
                 vendor: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a LifecycleWatch resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] channel_ids: Notification channels to alert. Write-only: the API does not return these on read.
        :param pulumi.Input[bool] notify30d: Notify 30 days before end-of-life.
        :param pulumi.Input[bool] notify7d: Notify 7 days before end-of-life.
        :param pulumi.Input[bool] notify90d: Notify 90 days before end-of-life.
        :param pulumi.Input[bool] notify_on_new: Notify when a new release/version appears.
        :param pulumi.Input[int] organization_id: The organization this watch belongs to.
        :param pulumi.Input[str] platform: Optional platform qualifier (part of the watch's identity).
        :param pulumi.Input[str] resource_id: Optional specific resource id to watch (part of the watch's identity).
        :param pulumi.Input[str] resource_type: The kind of resource being watched (default 'ai_model').
        :param pulumi.Input[str] vendor: The vendor being watched (e.g. 'openai', 'anthropic').
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: LifecycleWatchArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a LifecycleWatch resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param LifecycleWatchArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(LifecycleWatchArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 notify30d: Optional[pulumi.Input[bool]] = None,
                 notify7d: Optional[pulumi.Input[bool]] = None,
                 notify90d: Optional[pulumi.Input[bool]] = None,
                 notify_on_new: Optional[pulumi.Input[bool]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 platform: Optional[pulumi.Input[str]] = None,
                 resource_id: Optional[pulumi.Input[str]] = None,
                 resource_type: Optional[pulumi.Input[str]] = None,
                 vendor: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = LifecycleWatchArgs.__new__(LifecycleWatchArgs)

            __props__.__dict__["channel_ids"] = channel_ids
            __props__.__dict__["notify30d"] = notify30d
            __props__.__dict__["notify7d"] = notify7d
            __props__.__dict__["notify90d"] = notify90d
            __props__.__dict__["notify_on_new"] = notify_on_new
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["platform"] = platform
            __props__.__dict__["resource_id"] = resource_id
            __props__.__dict__["resource_type"] = resource_type
            if vendor is None and not opts.urn:
                raise TypeError("Missing required property 'vendor'")
            __props__.__dict__["vendor"] = vendor
        super(LifecycleWatch, __self__).__init__(
            'systeam:index/lifecycleWatch:LifecycleWatch',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
            notify30d: Optional[pulumi.Input[bool]] = None,
            notify7d: Optional[pulumi.Input[bool]] = None,
            notify90d: Optional[pulumi.Input[bool]] = None,
            notify_on_new: Optional[pulumi.Input[bool]] = None,
            organization_id: Optional[pulumi.Input[int]] = None,
            platform: Optional[pulumi.Input[str]] = None,
            resource_id: Optional[pulumi.Input[str]] = None,
            resource_type: Optional[pulumi.Input[str]] = None,
            vendor: Optional[pulumi.Input[str]] = None) -> 'LifecycleWatch':
        """
        Get an existing LifecycleWatch resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] channel_ids: Notification channels to alert. Write-only: the API does not return these on read.
        :param pulumi.Input[bool] notify30d: Notify 30 days before end-of-life.
        :param pulumi.Input[bool] notify7d: Notify 7 days before end-of-life.
        :param pulumi.Input[bool] notify90d: Notify 90 days before end-of-life.
        :param pulumi.Input[bool] notify_on_new: Notify when a new release/version appears.
        :param pulumi.Input[int] organization_id: The organization this watch belongs to.
        :param pulumi.Input[str] platform: Optional platform qualifier (part of the watch's identity).
        :param pulumi.Input[str] resource_id: Optional specific resource id to watch (part of the watch's identity).
        :param pulumi.Input[str] resource_type: The kind of resource being watched (default 'ai_model').
        :param pulumi.Input[str] vendor: The vendor being watched (e.g. 'openai', 'anthropic').
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _LifecycleWatchState.__new__(_LifecycleWatchState)

        __props__.__dict__["channel_ids"] = channel_ids
        __props__.__dict__["notify30d"] = notify30d
        __props__.__dict__["notify7d"] = notify7d
        __props__.__dict__["notify90d"] = notify90d
        __props__.__dict__["notify_on_new"] = notify_on_new
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["platform"] = platform
        __props__.__dict__["resource_id"] = resource_id
        __props__.__dict__["resource_type"] = resource_type
        __props__.__dict__["vendor"] = vendor
        return LifecycleWatch(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="channelIds")
    def channel_ids(self) -> pulumi.Output[Optional[Sequence[int]]]:
        """
        Notification channels to alert. Write-only: the API does not return these on read.
        """
        return pulumi.get(self, "channel_ids")

    @property
    @pulumi.getter
    def notify30d(self) -> pulumi.Output[bool]:
        """
        Notify 30 days before end-of-life.
        """
        return pulumi.get(self, "notify30d")

    @property
    @pulumi.getter
    def notify7d(self) -> pulumi.Output[bool]:
        """
        Notify 7 days before end-of-life.
        """
        return pulumi.get(self, "notify7d")

    @property
    @pulumi.getter
    def notify90d(self) -> pulumi.Output[bool]:
        """
        Notify 90 days before end-of-life.
        """
        return pulumi.get(self, "notify90d")

    @property
    @pulumi.getter(name="notifyOnNew")
    def notify_on_new(self) -> pulumi.Output[bool]:
        """
        Notify when a new release/version appears.
        """
        return pulumi.get(self, "notify_on_new")

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[int]:
        """
        The organization this watch belongs to.
        """
        return pulumi.get(self, "organization_id")

    @property
    @pulumi.getter
    def platform(self) -> pulumi.Output[Optional[str]]:
        """
        Optional platform qualifier (part of the watch's identity).
        """
        return pulumi.get(self, "platform")

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Output[Optional[str]]:
        """
        Optional specific resource id to watch (part of the watch's identity).
        """
        return pulumi.get(self, "resource_id")

    @property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> pulumi.Output[str]:
        """
        The kind of resource being watched (default 'ai_model').
        """
        return pulumi.get(self, "resource_type")

    @property
    @pulumi.getter
    def vendor(self) -> pulumi.Output[str]:
        """
        The vendor being watched (e.g. 'openai', 'anthropic').
        """
        return pulumi.get(self, "vendor")

