# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['OncallScheduleArgs', 'OncallSchedule']

@pulumi.input_type
class OncallScheduleArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 organization_id: pulumi.Input[int],
                 is_active: Optional[pulumi.Input[bool]] = None,
                 participants: Optional[pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]]] = None,
                 rotation_type: Optional[pulumi.Input[str]] = None,
                 timezone: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a OncallSchedule resource.
        :param pulumi.Input[str] name: The name of the on-call schedule.
        :param pulumi.Input[int] organization_id: The ID of the organization this schedule belongs to.
        :param pulumi.Input[bool] is_active: Whether the on-call schedule is active.
        :param pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]] participants: Participants in the on-call rotation.
        :param pulumi.Input[str] rotation_type: Rotation type: DAILY or WEEKLY.
        :param pulumi.Input[str] timezone: Timezone for the schedule (e.g. 'Europe/Warsaw', 'UTC').
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "organization_id", organization_id)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if participants is not None:
            pulumi.set(__self__, "participants", participants)
        if rotation_type is not None:
            pulumi.set(__self__, "rotation_type", rotation_type)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        The name of the on-call schedule.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[int]:
        """
        The ID of the organization this schedule belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the on-call schedule is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter
    def participants(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]]]:
        """
        Participants in the on-call rotation.
        """
        return pulumi.get(self, "participants")

    @participants.setter
    def participants(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]]]):
        pulumi.set(self, "participants", value)

    @property
    @pulumi.getter(name="rotationType")
    def rotation_type(self) -> Optional[pulumi.Input[str]]:
        """
        Rotation type: DAILY or WEEKLY.
        """
        return pulumi.get(self, "rotation_type")

    @rotation_type.setter
    def rotation_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "rotation_type", value)

    @property
    @pulumi.getter
    def timezone(self) -> Optional[pulumi.Input[str]]:
        """
        Timezone for the schedule (e.g. 'Europe/Warsaw', 'UTC').
        """
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "timezone", value)


@pulumi.input_type
class _OncallScheduleState:
    def __init__(__self__, *,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 participants: Optional[pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]]] = None,
                 rotation_type: Optional[pulumi.Input[str]] = None,
                 timezone: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering OncallSchedule resources.
        :param pulumi.Input[bool] is_active: Whether the on-call schedule is active.
        :param pulumi.Input[str] name: The name of the on-call schedule.
        :param pulumi.Input[int] organization_id: The ID of the organization this schedule belongs to.
        :param pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]] participants: Participants in the on-call rotation.
        :param pulumi.Input[str] rotation_type: Rotation type: DAILY or WEEKLY.
        :param pulumi.Input[str] timezone: Timezone for the schedule (e.g. 'Europe/Warsaw', 'UTC').
        """
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if participants is not None:
            pulumi.set(__self__, "participants", participants)
        if rotation_type is not None:
            pulumi.set(__self__, "rotation_type", rotation_type)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the on-call schedule is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the on-call schedule.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[int]]:
        """
        The ID of the organization this schedule belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def participants(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]]]:
        """
        Participants in the on-call rotation.
        """
        return pulumi.get(self, "participants")

    @participants.setter
    def participants(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['OncallScheduleParticipantArgs']]]]):
        pulumi.set(self, "participants", value)

    @property
    @pulumi.getter(name="rotationType")
    def rotation_type(self) -> Optional[pulumi.Input[str]]:
        """
        Rotation type: DAILY or WEEKLY.
        """
        return pulumi.get(self, "rotation_type")

    @rotation_type.setter
    def rotation_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "rotation_type", value)

    @property
    @pulumi.getter
    def timezone(self) -> Optional[pulumi.Input[str]]:
        """
        Timezone for the schedule (e.g. 'Europe/Warsaw', 'UTC').
        """
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "timezone", value)


class OncallSchedule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 participants: Optional[pulumi.Input[Sequence[pulumi.Input[Union['OncallScheduleParticipantArgs', 'OncallScheduleParticipantArgsDict']]]]] = None,
                 rotation_type: Optional[pulumi.Input[str]] = None,
                 timezone: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a OncallSchedule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] is_active: Whether the on-call schedule is active.
        :param pulumi.Input[str] name: The name of the on-call schedule.
        :param pulumi.Input[int] organization_id: The ID of the organization this schedule belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[Union['OncallScheduleParticipantArgs', 'OncallScheduleParticipantArgsDict']]]] participants: Participants in the on-call rotation.
        :param pulumi.Input[str] rotation_type: Rotation type: DAILY or WEEKLY.
        :param pulumi.Input[str] timezone: Timezone for the schedule (e.g. 'Europe/Warsaw', 'UTC').
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OncallScheduleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a OncallSchedule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param OncallScheduleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OncallScheduleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 participants: Optional[pulumi.Input[Sequence[pulumi.Input[Union['OncallScheduleParticipantArgs', 'OncallScheduleParticipantArgsDict']]]]] = None,
                 rotation_type: Optional[pulumi.Input[str]] = None,
                 timezone: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OncallScheduleArgs.__new__(OncallScheduleArgs)

            __props__.__dict__["is_active"] = is_active
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["participants"] = participants
            __props__.__dict__["rotation_type"] = rotation_type
            __props__.__dict__["timezone"] = timezone
        super(OncallSchedule, __self__).__init__(
            'systeam:index/oncallSchedule:OncallSchedule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            is_active: Optional[pulumi.Input[bool]] = None,
            name: Optional[pulumi.Input[str]] = None,
            organization_id: Optional[pulumi.Input[int]] = None,
            participants: Optional[pulumi.Input[Sequence[pulumi.Input[Union['OncallScheduleParticipantArgs', 'OncallScheduleParticipantArgsDict']]]]] = None,
            rotation_type: Optional[pulumi.Input[str]] = None,
            timezone: Optional[pulumi.Input[str]] = None) -> 'OncallSchedule':
        """
        Get an existing OncallSchedule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] is_active: Whether the on-call schedule is active.
        :param pulumi.Input[str] name: The name of the on-call schedule.
        :param pulumi.Input[int] organization_id: The ID of the organization this schedule belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[Union['OncallScheduleParticipantArgs', 'OncallScheduleParticipantArgsDict']]]] participants: Participants in the on-call rotation.
        :param pulumi.Input[str] rotation_type: Rotation type: DAILY or WEEKLY.
        :param pulumi.Input[str] timezone: Timezone for the schedule (e.g. 'Europe/Warsaw', 'UTC').
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OncallScheduleState.__new__(_OncallScheduleState)

        __props__.__dict__["is_active"] = is_active
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["participants"] = participants
        __props__.__dict__["rotation_type"] = rotation_type
        __props__.__dict__["timezone"] = timezone
        return OncallSchedule(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[bool]:
        """
        Whether the on-call schedule is active.
        """
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The name of the on-call schedule.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[int]:
        """
        The ID of the organization this schedule belongs to.
        """
        return pulumi.get(self, "organization_id")

    @property
    @pulumi.getter
    def participants(self) -> pulumi.Output[Optional[Sequence['outputs.OncallScheduleParticipant']]]:
        """
        Participants in the on-call rotation.
        """
        return pulumi.get(self, "participants")

    @property
    @pulumi.getter(name="rotationType")
    def rotation_type(self) -> pulumi.Output[str]:
        """
        Rotation type: DAILY or WEEKLY.
        """
        return pulumi.get(self, "rotation_type")

    @property
    @pulumi.getter
    def timezone(self) -> pulumi.Output[str]:
        """
        Timezone for the schedule (e.g. 'Europe/Warsaw', 'UTC').
        """
        return pulumi.get(self, "timezone")

