# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'EscalationPolicyStep',
    'OncallScheduleParticipant',
    'PlaybookStep',
]

@pulumi.output_type
class EscalationPolicyStep(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "stepOrder":
            suggest = "step_order"
        elif key == "targetType":
            suggest = "target_type"
        elif key == "delayMinutes":
            suggest = "delay_minutes"
        elif key == "targetChannelId":
            suggest = "target_channel_id"
        elif key == "targetScheduleId":
            suggest = "target_schedule_id"
        elif key == "targetUserId":
            suggest = "target_user_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in EscalationPolicyStep. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        EscalationPolicyStep.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        EscalationPolicyStep.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 step_order: int,
                 target_type: str,
                 delay_minutes: Optional[int] = None,
                 target_channel_id: Optional[int] = None,
                 target_schedule_id: Optional[int] = None,
                 target_user_id: Optional[int] = None):
        """
        :param int step_order: Order of this step in the escalation chain (1-based).
        :param str target_type: Type of escalation target: user, schedule, or channel.
        :param int delay_minutes: Delay in minutes before escalating to this step.
        :param int target_channel_id: ID of the target notification channel (when target_type is 'channel').
        :param int target_schedule_id: ID of the target on-call schedule (when target_type is 'schedule').
        :param int target_user_id: ID of the target user (when target_type is 'user').
        """
        pulumi.set(__self__, "step_order", step_order)
        pulumi.set(__self__, "target_type", target_type)
        if delay_minutes is not None:
            pulumi.set(__self__, "delay_minutes", delay_minutes)
        if target_channel_id is not None:
            pulumi.set(__self__, "target_channel_id", target_channel_id)
        if target_schedule_id is not None:
            pulumi.set(__self__, "target_schedule_id", target_schedule_id)
        if target_user_id is not None:
            pulumi.set(__self__, "target_user_id", target_user_id)

    @property
    @pulumi.getter(name="stepOrder")
    def step_order(self) -> int:
        """
        Order of this step in the escalation chain (1-based).
        """
        return pulumi.get(self, "step_order")

    @property
    @pulumi.getter(name="targetType")
    def target_type(self) -> str:
        """
        Type of escalation target: user, schedule, or channel.
        """
        return pulumi.get(self, "target_type")

    @property
    @pulumi.getter(name="delayMinutes")
    def delay_minutes(self) -> Optional[int]:
        """
        Delay in minutes before escalating to this step.
        """
        return pulumi.get(self, "delay_minutes")

    @property
    @pulumi.getter(name="targetChannelId")
    def target_channel_id(self) -> Optional[int]:
        """
        ID of the target notification channel (when target_type is 'channel').
        """
        return pulumi.get(self, "target_channel_id")

    @property
    @pulumi.getter(name="targetScheduleId")
    def target_schedule_id(self) -> Optional[int]:
        """
        ID of the target on-call schedule (when target_type is 'schedule').
        """
        return pulumi.get(self, "target_schedule_id")

    @property
    @pulumi.getter(name="targetUserId")
    def target_user_id(self) -> Optional[int]:
        """
        ID of the target user (when target_type is 'user').
        """
        return pulumi.get(self, "target_user_id")


@pulumi.output_type
class OncallScheduleParticipant(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "userId":
            suggest = "user_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in OncallScheduleParticipant. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        OncallScheduleParticipant.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        OncallScheduleParticipant.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 user_id: int,
                 position: Optional[int] = None):
        """
        :param int user_id: ID of the participant user.
        :param int position: Position in the rotation order.
        """
        pulumi.set(__self__, "user_id", user_id)
        if position is not None:
            pulumi.set(__self__, "position", position)

    @property
    @pulumi.getter(name="userId")
    def user_id(self) -> int:
        """
        ID of the participant user.
        """
        return pulumi.get(self, "user_id")

    @property
    @pulumi.getter
    def position(self) -> Optional[int]:
        """
        Position in the rotation order.
        """
        return pulumi.get(self, "position")


@pulumi.output_type
class PlaybookStep(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "actionType":
            suggest = "action_type"
        elif key == "stepOrder":
            suggest = "step_order"
        elif key == "isManual":
            suggest = "is_manual"
        elif key == "parallelGroup":
            suggest = "parallel_group"
        elif key == "timeoutSeconds":
            suggest = "timeout_seconds"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PlaybookStep. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PlaybookStep.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PlaybookStep.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 action_type: str,
                 name: str,
                 step_order: int,
                 conditions: Optional[str] = None,
                 config: Optional[str] = None,
                 is_manual: Optional[bool] = None,
                 parallel_group: Optional[str] = None,
                 timeout_seconds: Optional[int] = None):
        """
        :param str action_type: The action to run. One of: add_responders, set_priority, set_severity, setup_war_room, create_jira_ticket, auto_ack, auto_resolve, update_status_page, notify_subscribers, run_escalation, outbound_webhook, create_slack_channel, add_links, title_enrichment, send_custom_notification, manual_step.
        :param str name: Human-readable step name.
        :param int step_order: Position of this step in the run (1-based).
        :param str conditions: Optional JSON array of conditions gating this step.
        :param str config: Action-specific configuration as a JSON object.
        :param bool is_manual: Whether the step waits for manual completion.
        :param str parallel_group: Steps sharing a parallel_group run concurrently.
        :param int timeout_seconds: Step timeout in seconds (1-120).
        """
        pulumi.set(__self__, "action_type", action_type)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "step_order", step_order)
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if is_manual is not None:
            pulumi.set(__self__, "is_manual", is_manual)
        if parallel_group is not None:
            pulumi.set(__self__, "parallel_group", parallel_group)
        if timeout_seconds is not None:
            pulumi.set(__self__, "timeout_seconds", timeout_seconds)

    @property
    @pulumi.getter(name="actionType")
    def action_type(self) -> str:
        """
        The action to run. One of: add_responders, set_priority, set_severity, setup_war_room, create_jira_ticket, auto_ack, auto_resolve, update_status_page, notify_subscribers, run_escalation, outbound_webhook, create_slack_channel, add_links, title_enrichment, send_custom_notification, manual_step.
        """
        return pulumi.get(self, "action_type")

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        Human-readable step name.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="stepOrder")
    def step_order(self) -> int:
        """
        Position of this step in the run (1-based).
        """
        return pulumi.get(self, "step_order")

    @property
    @pulumi.getter
    def conditions(self) -> Optional[str]:
        """
        Optional JSON array of conditions gating this step.
        """
        return pulumi.get(self, "conditions")

    @property
    @pulumi.getter
    def config(self) -> Optional[str]:
        """
        Action-specific configuration as a JSON object.
        """
        return pulumi.get(self, "config")

    @property
    @pulumi.getter(name="isManual")
    def is_manual(self) -> Optional[bool]:
        """
        Whether the step waits for manual completion.
        """
        return pulumi.get(self, "is_manual")

    @property
    @pulumi.getter(name="parallelGroup")
    def parallel_group(self) -> Optional[str]:
        """
        Steps sharing a parallel_group run concurrently.
        """
        return pulumi.get(self, "parallel_group")

    @property
    @pulumi.getter(name="timeoutSeconds")
    def timeout_seconds(self) -> Optional[int]:
        """
        Step timeout in seconds (1-120).
        """
        return pulumi.get(self, "timeout_seconds")


