# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['PlaybookArgs', 'Playbook']

@pulumi.input_type
class PlaybookArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 organization_id: pulumi.Input[int],
                 trigger_type: pulumi.Input[str],
                 description: Optional[pulumi.Input[str]] = None,
                 service_id: Optional[pulumi.Input[int]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]]] = None,
                 suppress_default_notifications: Optional[pulumi.Input[bool]] = None,
                 trigger_conditions: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Playbook resource.
        :param pulumi.Input[str] name: The playbook name (1-200 chars).
        :param pulumi.Input[int] organization_id: The organization this playbook belongs to.
        :param pulumi.Input[str] trigger_type: What fires the playbook: check_status_change, inbound_incident_created, inbound_status_change, manual.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[int] service_id: Optionally scope the playbook to a service.
        :param pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]] steps: Ordered steps executed when the playbook runs.
        :param pulumi.Input[bool] suppress_default_notifications: Suppress the product's default notifications while this playbook runs.
        :param pulumi.Input[str] trigger_conditions: JSON object of extra conditions the trigger must match.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "organization_id", organization_id)
        pulumi.set(__self__, "trigger_type", trigger_type)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if service_id is not None:
            pulumi.set(__self__, "service_id", service_id)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)
        if suppress_default_notifications is not None:
            pulumi.set(__self__, "suppress_default_notifications", suppress_default_notifications)
        if trigger_conditions is not None:
            pulumi.set(__self__, "trigger_conditions", trigger_conditions)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        The playbook name (1-200 chars).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[int]:
        """
        The organization this playbook belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter(name="triggerType")
    def trigger_type(self) -> pulumi.Input[str]:
        """
        What fires the playbook: check_status_change, inbound_incident_created, inbound_status_change, manual.
        """
        return pulumi.get(self, "trigger_type")

    @trigger_type.setter
    def trigger_type(self, value: pulumi.Input[str]):
        pulumi.set(self, "trigger_type", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        An optional description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> Optional[pulumi.Input[int]]:
        """
        Optionally scope the playbook to a service.
        """
        return pulumi.get(self, "service_id")

    @service_id.setter
    def service_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "service_id", value)

    @property
    @pulumi.getter
    def steps(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]]]:
        """
        Ordered steps executed when the playbook runs.
        """
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]]]):
        pulumi.set(self, "steps", value)

    @property
    @pulumi.getter(name="suppressDefaultNotifications")
    def suppress_default_notifications(self) -> Optional[pulumi.Input[bool]]:
        """
        Suppress the product's default notifications while this playbook runs.
        """
        return pulumi.get(self, "suppress_default_notifications")

    @suppress_default_notifications.setter
    def suppress_default_notifications(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "suppress_default_notifications", value)

    @property
    @pulumi.getter(name="triggerConditions")
    def trigger_conditions(self) -> Optional[pulumi.Input[str]]:
        """
        JSON object of extra conditions the trigger must match.
        """
        return pulumi.get(self, "trigger_conditions")

    @trigger_conditions.setter
    def trigger_conditions(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "trigger_conditions", value)


@pulumi.input_type
class _PlaybookState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[str]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 service_id: Optional[pulumi.Input[int]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]]] = None,
                 suppress_default_notifications: Optional[pulumi.Input[bool]] = None,
                 trigger_conditions: Optional[pulumi.Input[str]] = None,
                 trigger_type: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering Playbook resources.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[bool] is_active: Whether the playbook is active.
        :param pulumi.Input[str] name: The playbook name (1-200 chars).
        :param pulumi.Input[int] organization_id: The organization this playbook belongs to.
        :param pulumi.Input[int] service_id: Optionally scope the playbook to a service.
        :param pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]] steps: Ordered steps executed when the playbook runs.
        :param pulumi.Input[bool] suppress_default_notifications: Suppress the product's default notifications while this playbook runs.
        :param pulumi.Input[str] trigger_conditions: JSON object of extra conditions the trigger must match.
        :param pulumi.Input[str] trigger_type: What fires the playbook: check_status_change, inbound_incident_created, inbound_status_change, manual.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if service_id is not None:
            pulumi.set(__self__, "service_id", service_id)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)
        if suppress_default_notifications is not None:
            pulumi.set(__self__, "suppress_default_notifications", suppress_default_notifications)
        if trigger_conditions is not None:
            pulumi.set(__self__, "trigger_conditions", trigger_conditions)
        if trigger_type is not None:
            pulumi.set(__self__, "trigger_type", trigger_type)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        An optional description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the playbook is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The playbook name (1-200 chars).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[int]]:
        """
        The organization this playbook belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> Optional[pulumi.Input[int]]:
        """
        Optionally scope the playbook to a service.
        """
        return pulumi.get(self, "service_id")

    @service_id.setter
    def service_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "service_id", value)

    @property
    @pulumi.getter
    def steps(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]]]:
        """
        Ordered steps executed when the playbook runs.
        """
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['PlaybookStepArgs']]]]):
        pulumi.set(self, "steps", value)

    @property
    @pulumi.getter(name="suppressDefaultNotifications")
    def suppress_default_notifications(self) -> Optional[pulumi.Input[bool]]:
        """
        Suppress the product's default notifications while this playbook runs.
        """
        return pulumi.get(self, "suppress_default_notifications")

    @suppress_default_notifications.setter
    def suppress_default_notifications(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "suppress_default_notifications", value)

    @property
    @pulumi.getter(name="triggerConditions")
    def trigger_conditions(self) -> Optional[pulumi.Input[str]]:
        """
        JSON object of extra conditions the trigger must match.
        """
        return pulumi.get(self, "trigger_conditions")

    @trigger_conditions.setter
    def trigger_conditions(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "trigger_conditions", value)

    @property
    @pulumi.getter(name="triggerType")
    def trigger_type(self) -> Optional[pulumi.Input[str]]:
        """
        What fires the playbook: check_status_change, inbound_incident_created, inbound_status_change, manual.
        """
        return pulumi.get(self, "trigger_type")

    @trigger_type.setter
    def trigger_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "trigger_type", value)


class Playbook(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 service_id: Optional[pulumi.Input[int]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input[Union['PlaybookStepArgs', 'PlaybookStepArgsDict']]]]] = None,
                 suppress_default_notifications: Optional[pulumi.Input[bool]] = None,
                 trigger_conditions: Optional[pulumi.Input[str]] = None,
                 trigger_type: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a Playbook resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[str] name: The playbook name (1-200 chars).
        :param pulumi.Input[int] organization_id: The organization this playbook belongs to.
        :param pulumi.Input[int] service_id: Optionally scope the playbook to a service.
        :param pulumi.Input[Sequence[pulumi.Input[Union['PlaybookStepArgs', 'PlaybookStepArgsDict']]]] steps: Ordered steps executed when the playbook runs.
        :param pulumi.Input[bool] suppress_default_notifications: Suppress the product's default notifications while this playbook runs.
        :param pulumi.Input[str] trigger_conditions: JSON object of extra conditions the trigger must match.
        :param pulumi.Input[str] trigger_type: What fires the playbook: check_status_change, inbound_incident_created, inbound_status_change, manual.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PlaybookArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Playbook resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PlaybookArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PlaybookArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 service_id: Optional[pulumi.Input[int]] = None,
                 steps: Optional[pulumi.Input[Sequence[pulumi.Input[Union['PlaybookStepArgs', 'PlaybookStepArgsDict']]]]] = None,
                 suppress_default_notifications: Optional[pulumi.Input[bool]] = None,
                 trigger_conditions: Optional[pulumi.Input[str]] = None,
                 trigger_type: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PlaybookArgs.__new__(PlaybookArgs)

            __props__.__dict__["description"] = description
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["service_id"] = service_id
            __props__.__dict__["steps"] = steps
            __props__.__dict__["suppress_default_notifications"] = suppress_default_notifications
            __props__.__dict__["trigger_conditions"] = trigger_conditions
            if trigger_type is None and not opts.urn:
                raise TypeError("Missing required property 'trigger_type'")
            __props__.__dict__["trigger_type"] = trigger_type
            __props__.__dict__["is_active"] = None
        super(Playbook, __self__).__init__(
            'systeam:index/playbook:Playbook',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[str]] = None,
            is_active: Optional[pulumi.Input[bool]] = None,
            name: Optional[pulumi.Input[str]] = None,
            organization_id: Optional[pulumi.Input[int]] = None,
            service_id: Optional[pulumi.Input[int]] = None,
            steps: Optional[pulumi.Input[Sequence[pulumi.Input[Union['PlaybookStepArgs', 'PlaybookStepArgsDict']]]]] = None,
            suppress_default_notifications: Optional[pulumi.Input[bool]] = None,
            trigger_conditions: Optional[pulumi.Input[str]] = None,
            trigger_type: Optional[pulumi.Input[str]] = None) -> 'Playbook':
        """
        Get an existing Playbook resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[bool] is_active: Whether the playbook is active.
        :param pulumi.Input[str] name: The playbook name (1-200 chars).
        :param pulumi.Input[int] organization_id: The organization this playbook belongs to.
        :param pulumi.Input[int] service_id: Optionally scope the playbook to a service.
        :param pulumi.Input[Sequence[pulumi.Input[Union['PlaybookStepArgs', 'PlaybookStepArgsDict']]]] steps: Ordered steps executed when the playbook runs.
        :param pulumi.Input[bool] suppress_default_notifications: Suppress the product's default notifications while this playbook runs.
        :param pulumi.Input[str] trigger_conditions: JSON object of extra conditions the trigger must match.
        :param pulumi.Input[str] trigger_type: What fires the playbook: check_status_change, inbound_incident_created, inbound_status_change, manual.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PlaybookState.__new__(_PlaybookState)

        __props__.__dict__["description"] = description
        __props__.__dict__["is_active"] = is_active
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["service_id"] = service_id
        __props__.__dict__["steps"] = steps
        __props__.__dict__["suppress_default_notifications"] = suppress_default_notifications
        __props__.__dict__["trigger_conditions"] = trigger_conditions
        __props__.__dict__["trigger_type"] = trigger_type
        return Playbook(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[str]:
        """
        An optional description.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[bool]:
        """
        Whether the playbook is active.
        """
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The playbook name (1-200 chars).
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[int]:
        """
        The organization this playbook belongs to.
        """
        return pulumi.get(self, "organization_id")

    @property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> pulumi.Output[Optional[int]]:
        """
        Optionally scope the playbook to a service.
        """
        return pulumi.get(self, "service_id")

    @property
    @pulumi.getter
    def steps(self) -> pulumi.Output[Optional[Sequence['outputs.PlaybookStep']]]:
        """
        Ordered steps executed when the playbook runs.
        """
        return pulumi.get(self, "steps")

    @property
    @pulumi.getter(name="suppressDefaultNotifications")
    def suppress_default_notifications(self) -> pulumi.Output[bool]:
        """
        Suppress the product's default notifications while this playbook runs.
        """
        return pulumi.get(self, "suppress_default_notifications")

    @property
    @pulumi.getter(name="triggerConditions")
    def trigger_conditions(self) -> pulumi.Output[str]:
        """
        JSON object of extra conditions the trigger must match.
        """
        return pulumi.get(self, "trigger_conditions")

    @property
    @pulumi.getter(name="triggerType")
    def trigger_type(self) -> pulumi.Output[str]:
        """
        What fires the playbook: check_status_change, inbound_incident_created, inbound_status_change, manual.
        """
        return pulumi.get(self, "trigger_type")

