# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ServiceArgs', 'Service']

@pulumi.input_type
class ServiceArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 organization_id: pulumi.Input[int],
                 description: Optional[pulumi.Input[str]] = None,
                 docs_url: Optional[pulumi.Input[str]] = None,
                 escalation_policy_id: Optional[pulumi.Input[int]] = None,
                 notification_channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 owner_team_id: Optional[pulumi.Input[int]] = None,
                 repo_url: Optional[pulumi.Input[str]] = None,
                 tier: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Service resource.
        :param pulumi.Input[str] name: The service's display name.
        :param pulumi.Input[int] organization_id: The ID of the organization this service belongs to.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[str] docs_url: Link to the service's documentation.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy incidents on this service route to.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] notification_channel_ids: Notification channels attached to this service.
        :param pulumi.Input[int] owner_team_id: The team that owns this service.
        :param pulumi.Input[str] repo_url: Link to the service's source repository.
        :param pulumi.Input[str] tier: Criticality tier: P1 (highest) through P4.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "organization_id", organization_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if docs_url is not None:
            pulumi.set(__self__, "docs_url", docs_url)
        if escalation_policy_id is not None:
            pulumi.set(__self__, "escalation_policy_id", escalation_policy_id)
        if notification_channel_ids is not None:
            pulumi.set(__self__, "notification_channel_ids", notification_channel_ids)
        if owner_team_id is not None:
            pulumi.set(__self__, "owner_team_id", owner_team_id)
        if repo_url is not None:
            pulumi.set(__self__, "repo_url", repo_url)
        if tier is not None:
            pulumi.set(__self__, "tier", tier)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        The service's display name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[int]:
        """
        The ID of the organization this service belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        An optional description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="docsUrl")
    def docs_url(self) -> Optional[pulumi.Input[str]]:
        """
        Link to the service's documentation.
        """
        return pulumi.get(self, "docs_url")

    @docs_url.setter
    def docs_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "docs_url", value)

    @property
    @pulumi.getter(name="escalationPolicyId")
    def escalation_policy_id(self) -> Optional[pulumi.Input[int]]:
        """
        The escalation policy incidents on this service route to.
        """
        return pulumi.get(self, "escalation_policy_id")

    @escalation_policy_id.setter
    def escalation_policy_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "escalation_policy_id", value)

    @property
    @pulumi.getter(name="notificationChannelIds")
    def notification_channel_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        """
        Notification channels attached to this service.
        """
        return pulumi.get(self, "notification_channel_ids")

    @notification_channel_ids.setter
    def notification_channel_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "notification_channel_ids", value)

    @property
    @pulumi.getter(name="ownerTeamId")
    def owner_team_id(self) -> Optional[pulumi.Input[int]]:
        """
        The team that owns this service.
        """
        return pulumi.get(self, "owner_team_id")

    @owner_team_id.setter
    def owner_team_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "owner_team_id", value)

    @property
    @pulumi.getter(name="repoUrl")
    def repo_url(self) -> Optional[pulumi.Input[str]]:
        """
        Link to the service's source repository.
        """
        return pulumi.get(self, "repo_url")

    @repo_url.setter
    def repo_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "repo_url", value)

    @property
    @pulumi.getter
    def tier(self) -> Optional[pulumi.Input[str]]:
        """
        Criticality tier: P1 (highest) through P4.
        """
        return pulumi.get(self, "tier")

    @tier.setter
    def tier(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "tier", value)


@pulumi.input_type
class _ServiceState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[str]] = None,
                 docs_url: Optional[pulumi.Input[str]] = None,
                 escalation_policy_id: Optional[pulumi.Input[int]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 notification_channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 owner_team_id: Optional[pulumi.Input[int]] = None,
                 repo_url: Optional[pulumi.Input[str]] = None,
                 slug: Optional[pulumi.Input[str]] = None,
                 tier: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering Service resources.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[str] docs_url: Link to the service's documentation.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy incidents on this service route to.
        :param pulumi.Input[bool] is_active: Whether the service is active.
        :param pulumi.Input[str] name: The service's display name.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] notification_channel_ids: Notification channels attached to this service.
        :param pulumi.Input[int] organization_id: The ID of the organization this service belongs to.
        :param pulumi.Input[int] owner_team_id: The team that owns this service.
        :param pulumi.Input[str] repo_url: Link to the service's source repository.
        :param pulumi.Input[str] slug: URL-safe identifier, generated from the name.
        :param pulumi.Input[str] tier: Criticality tier: P1 (highest) through P4.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if docs_url is not None:
            pulumi.set(__self__, "docs_url", docs_url)
        if escalation_policy_id is not None:
            pulumi.set(__self__, "escalation_policy_id", escalation_policy_id)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notification_channel_ids is not None:
            pulumi.set(__self__, "notification_channel_ids", notification_channel_ids)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if owner_team_id is not None:
            pulumi.set(__self__, "owner_team_id", owner_team_id)
        if repo_url is not None:
            pulumi.set(__self__, "repo_url", repo_url)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if tier is not None:
            pulumi.set(__self__, "tier", tier)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        An optional description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="docsUrl")
    def docs_url(self) -> Optional[pulumi.Input[str]]:
        """
        Link to the service's documentation.
        """
        return pulumi.get(self, "docs_url")

    @docs_url.setter
    def docs_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "docs_url", value)

    @property
    @pulumi.getter(name="escalationPolicyId")
    def escalation_policy_id(self) -> Optional[pulumi.Input[int]]:
        """
        The escalation policy incidents on this service route to.
        """
        return pulumi.get(self, "escalation_policy_id")

    @escalation_policy_id.setter
    def escalation_policy_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "escalation_policy_id", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the service is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The service's display name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="notificationChannelIds")
    def notification_channel_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        """
        Notification channels attached to this service.
        """
        return pulumi.get(self, "notification_channel_ids")

    @notification_channel_ids.setter
    def notification_channel_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "notification_channel_ids", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[int]]:
        """
        The ID of the organization this service belongs to.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter(name="ownerTeamId")
    def owner_team_id(self) -> Optional[pulumi.Input[int]]:
        """
        The team that owns this service.
        """
        return pulumi.get(self, "owner_team_id")

    @owner_team_id.setter
    def owner_team_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "owner_team_id", value)

    @property
    @pulumi.getter(name="repoUrl")
    def repo_url(self) -> Optional[pulumi.Input[str]]:
        """
        Link to the service's source repository.
        """
        return pulumi.get(self, "repo_url")

    @repo_url.setter
    def repo_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "repo_url", value)

    @property
    @pulumi.getter
    def slug(self) -> Optional[pulumi.Input[str]]:
        """
        URL-safe identifier, generated from the name.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "slug", value)

    @property
    @pulumi.getter
    def tier(self) -> Optional[pulumi.Input[str]]:
        """
        Criticality tier: P1 (highest) through P4.
        """
        return pulumi.get(self, "tier")

    @tier.setter
    def tier(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "tier", value)


class Service(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 docs_url: Optional[pulumi.Input[str]] = None,
                 escalation_policy_id: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 notification_channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 owner_team_id: Optional[pulumi.Input[int]] = None,
                 repo_url: Optional[pulumi.Input[str]] = None,
                 tier: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Manages a service: an org-scoped catalog entry that incidents and checks attach to, with an owning team, an escalation policy, and notification channels.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[str] docs_url: Link to the service's documentation.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy incidents on this service route to.
        :param pulumi.Input[str] name: The service's display name.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] notification_channel_ids: Notification channels attached to this service.
        :param pulumi.Input[int] organization_id: The ID of the organization this service belongs to.
        :param pulumi.Input[int] owner_team_id: The team that owns this service.
        :param pulumi.Input[str] repo_url: Link to the service's source repository.
        :param pulumi.Input[str] tier: Criticality tier: P1 (highest) through P4.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a service: an org-scoped catalog entry that incidents and checks attach to, with an owning team, an escalation policy, and notification channels.

        :param str resource_name: The name of the resource.
        :param ServiceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 docs_url: Optional[pulumi.Input[str]] = None,
                 escalation_policy_id: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 notification_channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 owner_team_id: Optional[pulumi.Input[int]] = None,
                 repo_url: Optional[pulumi.Input[str]] = None,
                 tier: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceArgs.__new__(ServiceArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["docs_url"] = docs_url
            __props__.__dict__["escalation_policy_id"] = escalation_policy_id
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["notification_channel_ids"] = notification_channel_ids
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["owner_team_id"] = owner_team_id
            __props__.__dict__["repo_url"] = repo_url
            __props__.__dict__["tier"] = tier
            __props__.__dict__["is_active"] = None
            __props__.__dict__["slug"] = None
        super(Service, __self__).__init__(
            'systeam:index/service:Service',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[str]] = None,
            docs_url: Optional[pulumi.Input[str]] = None,
            escalation_policy_id: Optional[pulumi.Input[int]] = None,
            is_active: Optional[pulumi.Input[bool]] = None,
            name: Optional[pulumi.Input[str]] = None,
            notification_channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
            organization_id: Optional[pulumi.Input[int]] = None,
            owner_team_id: Optional[pulumi.Input[int]] = None,
            repo_url: Optional[pulumi.Input[str]] = None,
            slug: Optional[pulumi.Input[str]] = None,
            tier: Optional[pulumi.Input[str]] = None) -> 'Service':
        """
        Get an existing Service resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] description: An optional description.
        :param pulumi.Input[str] docs_url: Link to the service's documentation.
        :param pulumi.Input[int] escalation_policy_id: The escalation policy incidents on this service route to.
        :param pulumi.Input[bool] is_active: Whether the service is active.
        :param pulumi.Input[str] name: The service's display name.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] notification_channel_ids: Notification channels attached to this service.
        :param pulumi.Input[int] organization_id: The ID of the organization this service belongs to.
        :param pulumi.Input[int] owner_team_id: The team that owns this service.
        :param pulumi.Input[str] repo_url: Link to the service's source repository.
        :param pulumi.Input[str] slug: URL-safe identifier, generated from the name.
        :param pulumi.Input[str] tier: Criticality tier: P1 (highest) through P4.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServiceState.__new__(_ServiceState)

        __props__.__dict__["description"] = description
        __props__.__dict__["docs_url"] = docs_url
        __props__.__dict__["escalation_policy_id"] = escalation_policy_id
        __props__.__dict__["is_active"] = is_active
        __props__.__dict__["name"] = name
        __props__.__dict__["notification_channel_ids"] = notification_channel_ids
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["owner_team_id"] = owner_team_id
        __props__.__dict__["repo_url"] = repo_url
        __props__.__dict__["slug"] = slug
        __props__.__dict__["tier"] = tier
        return Service(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[str]:
        """
        An optional description.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="docsUrl")
    def docs_url(self) -> pulumi.Output[str]:
        """
        Link to the service's documentation.
        """
        return pulumi.get(self, "docs_url")

    @property
    @pulumi.getter(name="escalationPolicyId")
    def escalation_policy_id(self) -> pulumi.Output[Optional[int]]:
        """
        The escalation policy incidents on this service route to.
        """
        return pulumi.get(self, "escalation_policy_id")

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[bool]:
        """
        Whether the service is active.
        """
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The service's display name.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="notificationChannelIds")
    def notification_channel_ids(self) -> pulumi.Output[Sequence[int]]:
        """
        Notification channels attached to this service.
        """
        return pulumi.get(self, "notification_channel_ids")

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[int]:
        """
        The ID of the organization this service belongs to.
        """
        return pulumi.get(self, "organization_id")

    @property
    @pulumi.getter(name="ownerTeamId")
    def owner_team_id(self) -> pulumi.Output[Optional[int]]:
        """
        The team that owns this service.
        """
        return pulumi.get(self, "owner_team_id")

    @property
    @pulumi.getter(name="repoUrl")
    def repo_url(self) -> pulumi.Output[str]:
        """
        Link to the service's source repository.
        """
        return pulumi.get(self, "repo_url")

    @property
    @pulumi.getter
    def slug(self) -> pulumi.Output[str]:
        """
        URL-safe identifier, generated from the name.
        """
        return pulumi.get(self, "slug")

    @property
    @pulumi.getter
    def tier(self) -> pulumi.Output[str]:
        """
        Criticality tier: P1 (highest) through P4.
        """
        return pulumi.get(self, "tier")

