# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['StatusPageArgs', 'StatusPage']

@pulumi.input_type
class StatusPageArgs:
    def __init__(__self__, *,
                 check_ids: pulumi.Input[Sequence[pulumi.Input[int]]],
                 name: pulumi.Input[str],
                 organization_id: pulumi.Input[int],
                 slug: pulumi.Input[str],
                 custom_domain: Optional[pulumi.Input[str]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 is_public: Optional[pulumi.Input[bool]] = None,
                 logo_url: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a StatusPage resource.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] check_ids: List of check IDs to display on the status page.
        :param pulumi.Input[str] name: Status page name.
        :param pulumi.Input[int] organization_id: Organization ID that owns this status page.
        :param pulumi.Input[str] slug: URL-friendly identifier for the status page.
        :param pulumi.Input[str] custom_domain: Custom domain for the status page.
        :param pulumi.Input[str] description: Status page description.
        :param pulumi.Input[bool] is_active: Whether the status page is active.
        :param pulumi.Input[bool] is_public: Whether the status page is publicly accessible.
        :param pulumi.Input[str] logo_url: URL of the logo to display on the status page.
        """
        pulumi.set(__self__, "check_ids", check_ids)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "organization_id", organization_id)
        pulumi.set(__self__, "slug", slug)
        if custom_domain is not None:
            pulumi.set(__self__, "custom_domain", custom_domain)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if is_public is not None:
            pulumi.set(__self__, "is_public", is_public)
        if logo_url is not None:
            pulumi.set(__self__, "logo_url", logo_url)

    @property
    @pulumi.getter(name="checkIds")
    def check_ids(self) -> pulumi.Input[Sequence[pulumi.Input[int]]]:
        """
        List of check IDs to display on the status page.
        """
        return pulumi.get(self, "check_ids")

    @check_ids.setter
    def check_ids(self, value: pulumi.Input[Sequence[pulumi.Input[int]]]):
        pulumi.set(self, "check_ids", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        Status page name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[int]:
        """
        Organization ID that owns this status page.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[int]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def slug(self) -> pulumi.Input[str]:
        """
        URL-friendly identifier for the status page.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[str]):
        pulumi.set(self, "slug", value)

    @property
    @pulumi.getter(name="customDomain")
    def custom_domain(self) -> Optional[pulumi.Input[str]]:
        """
        Custom domain for the status page.
        """
        return pulumi.get(self, "custom_domain")

    @custom_domain.setter
    def custom_domain(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "custom_domain", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        Status page description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the status page is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the status page is publicly accessible.
        """
        return pulumi.get(self, "is_public")

    @is_public.setter
    def is_public(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_public", value)

    @property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> Optional[pulumi.Input[str]]:
        """
        URL of the logo to display on the status page.
        """
        return pulumi.get(self, "logo_url")

    @logo_url.setter
    def logo_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "logo_url", value)


@pulumi.input_type
class _StatusPageState:
    def __init__(__self__, *,
                 check_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 custom_domain: Optional[pulumi.Input[str]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 is_public: Optional[pulumi.Input[bool]] = None,
                 logo_url: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 slug: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering StatusPage resources.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] check_ids: List of check IDs to display on the status page.
        :param pulumi.Input[str] custom_domain: Custom domain for the status page.
        :param pulumi.Input[str] description: Status page description.
        :param pulumi.Input[bool] is_active: Whether the status page is active.
        :param pulumi.Input[bool] is_public: Whether the status page is publicly accessible.
        :param pulumi.Input[str] logo_url: URL of the logo to display on the status page.
        :param pulumi.Input[str] name: Status page name.
        :param pulumi.Input[int] organization_id: Organization ID that owns this status page.
        :param pulumi.Input[str] slug: URL-friendly identifier for the status page.
        """
        if check_ids is not None:
            pulumi.set(__self__, "check_ids", check_ids)
        if custom_domain is not None:
            pulumi.set(__self__, "custom_domain", custom_domain)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if is_public is not None:
            pulumi.set(__self__, "is_public", is_public)
        if logo_url is not None:
            pulumi.set(__self__, "logo_url", logo_url)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)

    @property
    @pulumi.getter(name="checkIds")
    def check_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]:
        """
        List of check IDs to display on the status page.
        """
        return pulumi.get(self, "check_ids")

    @check_ids.setter
    def check_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]]):
        pulumi.set(self, "check_ids", value)

    @property
    @pulumi.getter(name="customDomain")
    def custom_domain(self) -> Optional[pulumi.Input[str]]:
        """
        Custom domain for the status page.
        """
        return pulumi.get(self, "custom_domain")

    @custom_domain.setter
    def custom_domain(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "custom_domain", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        Status page description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the status page is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_active", value)

    @property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the status page is publicly accessible.
        """
        return pulumi.get(self, "is_public")

    @is_public.setter
    def is_public(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "is_public", value)

    @property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> Optional[pulumi.Input[str]]:
        """
        URL of the logo to display on the status page.
        """
        return pulumi.get(self, "logo_url")

    @logo_url.setter
    def logo_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "logo_url", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Status page name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[int]]:
        """
        Organization ID that owns this status page.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "organization_id", value)

    @property
    @pulumi.getter
    def slug(self) -> Optional[pulumi.Input[str]]:
        """
        URL-friendly identifier for the status page.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "slug", value)


class StatusPage(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 check_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 custom_domain: Optional[pulumi.Input[str]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 is_public: Optional[pulumi.Input[bool]] = None,
                 logo_url: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 slug: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a StatusPage resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] check_ids: List of check IDs to display on the status page.
        :param pulumi.Input[str] custom_domain: Custom domain for the status page.
        :param pulumi.Input[str] description: Status page description.
        :param pulumi.Input[bool] is_active: Whether the status page is active.
        :param pulumi.Input[bool] is_public: Whether the status page is publicly accessible.
        :param pulumi.Input[str] logo_url: URL of the logo to display on the status page.
        :param pulumi.Input[str] name: Status page name.
        :param pulumi.Input[int] organization_id: Organization ID that owns this status page.
        :param pulumi.Input[str] slug: URL-friendly identifier for the status page.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: StatusPageArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a StatusPage resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param StatusPageArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(StatusPageArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 check_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
                 custom_domain: Optional[pulumi.Input[str]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 is_active: Optional[pulumi.Input[bool]] = None,
                 is_public: Optional[pulumi.Input[bool]] = None,
                 logo_url: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization_id: Optional[pulumi.Input[int]] = None,
                 slug: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = StatusPageArgs.__new__(StatusPageArgs)

            if check_ids is None and not opts.urn:
                raise TypeError("Missing required property 'check_ids'")
            __props__.__dict__["check_ids"] = check_ids
            __props__.__dict__["custom_domain"] = custom_domain
            __props__.__dict__["description"] = description
            __props__.__dict__["is_active"] = is_active
            __props__.__dict__["is_public"] = is_public
            __props__.__dict__["logo_url"] = logo_url
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            if slug is None and not opts.urn:
                raise TypeError("Missing required property 'slug'")
            __props__.__dict__["slug"] = slug
        super(StatusPage, __self__).__init__(
            'systeam:index/statusPage:StatusPage',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            check_ids: Optional[pulumi.Input[Sequence[pulumi.Input[int]]]] = None,
            custom_domain: Optional[pulumi.Input[str]] = None,
            description: Optional[pulumi.Input[str]] = None,
            is_active: Optional[pulumi.Input[bool]] = None,
            is_public: Optional[pulumi.Input[bool]] = None,
            logo_url: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            organization_id: Optional[pulumi.Input[int]] = None,
            slug: Optional[pulumi.Input[str]] = None) -> 'StatusPage':
        """
        Get an existing StatusPage resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[int]]] check_ids: List of check IDs to display on the status page.
        :param pulumi.Input[str] custom_domain: Custom domain for the status page.
        :param pulumi.Input[str] description: Status page description.
        :param pulumi.Input[bool] is_active: Whether the status page is active.
        :param pulumi.Input[bool] is_public: Whether the status page is publicly accessible.
        :param pulumi.Input[str] logo_url: URL of the logo to display on the status page.
        :param pulumi.Input[str] name: Status page name.
        :param pulumi.Input[int] organization_id: Organization ID that owns this status page.
        :param pulumi.Input[str] slug: URL-friendly identifier for the status page.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _StatusPageState.__new__(_StatusPageState)

        __props__.__dict__["check_ids"] = check_ids
        __props__.__dict__["custom_domain"] = custom_domain
        __props__.__dict__["description"] = description
        __props__.__dict__["is_active"] = is_active
        __props__.__dict__["is_public"] = is_public
        __props__.__dict__["logo_url"] = logo_url
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["slug"] = slug
        return StatusPage(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="checkIds")
    def check_ids(self) -> pulumi.Output[Sequence[int]]:
        """
        List of check IDs to display on the status page.
        """
        return pulumi.get(self, "check_ids")

    @property
    @pulumi.getter(name="customDomain")
    def custom_domain(self) -> pulumi.Output[Optional[str]]:
        """
        Custom domain for the status page.
        """
        return pulumi.get(self, "custom_domain")

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[str]]:
        """
        Status page description.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[bool]:
        """
        Whether the status page is active.
        """
        return pulumi.get(self, "is_active")

    @property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> pulumi.Output[bool]:
        """
        Whether the status page is publicly accessible.
        """
        return pulumi.get(self, "is_public")

    @property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> pulumi.Output[Optional[str]]:
        """
        URL of the logo to display on the status page.
        """
        return pulumi.get(self, "logo_url")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Status page name.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[int]:
        """
        Organization ID that owns this status page.
        """
        return pulumi.get(self, "organization_id")

    @property
    @pulumi.getter
    def slug(self) -> pulumi.Output[str]:
        """
        URL-friendly identifier for the status page.
        """
        return pulumi.get(self, "slug")

